// ── 完整工具组合数据库 ─────────────────────────────────────
// 每个工具精确标注：网络要求 / 上手难度 / 月费 / 流转说明
import type { ComboTool, ComboStep, ToolCombo, NetAccess, Difficulty } from '@/types/combo'

// ── 工具构造器（简化写法）─────────────────────────────────
function t(
  name: string,
  logo: string,
  price: string,
  url: string,
  net: NetAccess,
  difficulty: Difficulty,
  tip?: string,
  slug?: string,
  priceCNY?: number,
  priceUSD?: number,
): ComboTool {
  return { name, logo, price, url, net, difficulty, tip, slug, priceCNY, priceUSD }
}

// ── 常用工具预定义（避免重复写参数）──────────────────────
const TOOLS = {
  doubao:      t('豆包',        '🫘', '免费',      'https://www.doubao.com',                    'cn',   1, '字节系，国内最易用，手机号注册即用',         'doubao',          0,    0),
  deepseek:    t('DeepSeek',   '🐋', '免费',      'https://chat.deepseek.com',                 'cn',   1, '国内免费，逻辑强，部分时段有限速',           'deepseek',        0,    0),
  kimi:        t('Kimi',       '🌙', '免费',      'https://kimi.moonshot.cn',                  'cn',   1, '长文档处理能力极强，支持上传PDF',            'kimi',            0,    0),
  claude35:    t('Claude',     '🤖', '$20/月',    'https://claude.ai',                         'vpn',  2, '文案质量最佳，中文流畅自然，需梯子',         'claude',          0,    20),
  chatgpt:     t('ChatGPT',   '💬', '$20/月',    'https://chat.openai.com',                   'vpn',  2, 'GPT-4o，综合能力强，需梯子+国外手机号',      'chatgpt',         0,    20),
  gemini:      t('Gemini',    '✨', '$20/月',    'https://gemini.google.com',                 'vpn',  2, 'Google出品，多模态强，需梯子',               'gemini',          0,    20),
  perplexity:  t('Perplexity','🔍', '$20/月',    'https://www.perplexity.ai',                 'vpn',  2, '联网搜索AI，找实时资料准确率高',             'perplexity',      0,    20),
  metaso:      t('秘塔搜索',   '🔎', '免费',      'https://metaso.cn',                         'cn',   1, '国内无广告AI搜索，找资料效率极高',           'metaso',          0,    0),
  jimeng:      t('即梦AI',    '🌙', '免费',      'https://jimeng.jianying.com',               'cn',   1, '字节系，免费额度每天可用，效果不错',          'jimeng',          0,    0),
  midjourney:  t('Midjourney','🎨', '$10/月起',  'https://www.midjourney.com',                'vpn',  3, '图像质量最佳，需梯子+Discord账号，学习曲线陡','midjourney',      72,   10),
  elevenlabs:  t('ElevenLabs','🎙️', '$5/月起',   'https://elevenlabs.io',                     'vpn',  2, '音色最自然，支持声音克隆，需梯子',           'elevenlabs',      36,   5),
  capcut:      t('剪映专业版', '✂️', '免费',      'https://www.capcut.cn',                     'cn',   2, '国内版，功能完整，AI字幕一键生成',           'capcut',          0,    0),
  heygen:      t('HeyGen',    '🎭', '$29/月',    'https://www.heygen.com',                    'vpn',  3, '数字人口播，克隆真人形象，需梯子',           'heygen',          0,    29),
  runway:      t('Runway',    '🎥', '$15/月起',  'https://runwayml.com',                      'vpn',  3, 'AI视频生成顶级，Gen-3效果好，需梯子',        'runway',          0,    15),
  kling:       t('可灵AI',    '🦋', '免费起',    'https://klingai.kuaishou.com',              'cn',   2, '快手出品，国内最好的AI视频工具，有免费额度',  'kling',           0,    0),
  canva:       t('Canva',     '🖌️', '免费/¥68月','https://www.canva.com',                    'both', 1, '中文版可用，模板丰富，免费版够用',            'canva',           0,    0),
  cursor:      t('Cursor',    '⌨️', '$20/月',    'https://cursor.sh',                         'both', 3, '目前最好的AI编程IDE，需要一定编程基础',       'cursor',          0,    20),
  copilot:     t('GitHub Copilot','🐙','$10/月', 'https://github.com/features/copilot',       'both', 3, '需要GitHub账号，VS Code插件形式',            'github-copilot',  0,    10),
  codeium:     t('Codeium',   '💚', '免费',      'https://codeium.com',                       'both', 2, '免费的Copilot替代，VS Code插件',             'codeium',         0,    0),
  vercel:      t('Vercel',    '▲',  '免费起',    'https://vercel.com',                        'both', 2, '前端部署神器，个人项目免费，国内访问稍慢',    undefined,         0,    0),
  gamma:       t('Gamma',     '📊', '$8/月起',   'https://gamma.app',                         'vpn',  1, '国内无法直连，需梯子，PPT生成质量极高',       'gamma',           58,   8),
  aippt:       t('AiPPT',    '📑', '免费起',    'https://www.aippt.cn',                      'cn',   1, '国内直连，基础功能免费，中文模板多',          'aippt',           0,    0),
  wpsai:       t('WPS AI',   '📄', '¥35/月',    'https://ai.wps.cn',                         'cn',   1, '深度整合Office，已有WPS用户直接升级',         'wps-ai',          35,   0),
  notion:      t('Notion AI', '📋', '$10/月',    'https://www.notion.so',                     'both', 2, '国内访问偶有问题，建议备好梯子',             'notion-ai',       0,    10),
  suno:        t('Suno',      '🎵', '免费/$8月', 'https://suno.com',                          'vpn',  1, '免费版每天50积分，需梯子，操作极简单',        'suno',            0,    8),
  udio:        t('Udio',      '🎶', '$10/月起',  'https://www.udio.com',                      'vpn',  2, '音乐风格控制更精细，需梯子',                 'udio',            0,    10),
  descript:    t('Descript',  '🎧', '$24/月',    'https://www.descript.com',                  'vpn',  2, '播客制作一体化神器，需梯子，功能学习1-2天',   'descript',        0,    24),
  buzzsprout:  t('Buzzsprout','📡', '$12/月',    'https://www.buzzsprout.com',                'vpn',  1, '自动分发到Spotify等20+平台，操作简单',        undefined,         0,    12),
  ximalaya:    t('小宇宙',    '🎧', '免费',      'https://www.xiaoyuzhoufm.com',              'cn',   1, '国内最大播客平台，流量和社区好',             undefined,         0,    0),
  iflytek:     t('讯飞听见',  '🎤', '免费限额',  'https://www.iflyrec.com',                  'cn',   1, '中文转写准确率高，免费有时长限制',           'iflytek',         0,    0),
  helium10:    t('Helium 10', '🔬', '$39/月',    'https://www.helium10.com',                  'vpn',  3, '亚马逊卖家必备选品工具，需梯子，功能复杂',   'helium10',        0,    39),
  tidio:       t('Tidio AI',  '🤝', '$29/月',    'https://www.tidio.com',                     'vpn',  2, 'AI客服工具，需要嵌入网站，需梯子',           undefined,         0,    29),
  copyai:      t('Copy.ai',   '✍️', '$49/月',    'https://www.copy.ai',                       'vpn',  2, '电商文案批量生成，需梯子',                   undefined,         0,    49),
  coze:        t('扣子(Coze)','🤖', '免费',      'https://www.coze.cn',                       'cn',   2, '字节系Bot平台，无需代码，国内版免费',         'coze',            0,    0),
  zapier:      t('Zapier',    '🔗', '$20/月',    'https://zapier.com',                        'vpn',  3, '连接7000+应用自动化，需梯子，配置需时间',     'zapier',          0,    20),
  dify:        t('Dify',      '⚙️', '免费自部署','https://dify.ai',                           'both', 4, '需要服务器部署，技术门槛较高',               'dify',            0,    0),
  feigua:      t('飞瓜数据',  '🍉', '¥99/月起',  'https://www.feigua.io',                     'cn',   2, '抖音/快手数据分析工具，选品利器',            'feigua',          99,   0),
  xiezuomao:   t('写作猫',    '🐱', '¥98/年',    'https://xiezuocat.com',                     'cn',   1, '专业中文校对+降重，年费折算每月8元',         'xiezuocat',       8,    0),
  boltNew:     t('Bolt.new',  '⚡', '$20/月',    'https://bolt.new',                          'vpn',  2, '浏览器全栈生成，无需本地环境，需梯子',        'bolt',            0,    20),
  supabase:    t('Supabase',  '🗄️', '免费起',    'https://supabase.com',                      'both', 3, '免费PostgreSQL数据库，需要一定技术背景',       undefined,         0,    0),
  sd:          t('Stable Diffusion','🌊','免费开源','https://stability.ai',                    'both', 5, '本地部署，需要显卡，技术门槛最高但完全可控',  'stable-diffusion',0,    0),
  grammarly:   t('Grammarly', '📖', '$12/月',    'https://www.grammarly.com',                 'vpn',  1, '英文语法检查，浏览器插件形式，需梯子',        'grammarly',       0,    12),
  klaviyo:     t('Klaviyo',   '📧', '$30/月',    'https://www.klaviyo.com',                   'vpn',  3, '邮件营销自动化，独立站标配，需梯子',          undefined,         0,    30),
  shopify:     t('Shopify',   '🛍️', '$39/月',    'https://www.shopify.com',                   'vpn',  2, '独立站建站平台，国内可访问管理后台',          undefined,         0,    39),
  adcreative:  t('AdCreative.ai','🎯','$29/月',  'https://www.adcreative.ai',                 'vpn',  2, '广告素材自动生成，高转化率，需梯子',          undefined,         0,    29),
  audacity:    t('Audacity',  '🎵', '免费开源',  'https://www.audacityteam.org',              'both', 3, '专业录音剪辑软件，需要学习基本操作',          undefined,         0,    0),
  adobeAud:    t('Adobe Audition','🎚️','¥168/月','https://www.adobe.com/products/audition.html','both',4,'专业级混音，Adobe订阅费，学习曲线较陡',       undefined,         168,  0),
  premiere:    t('Premiere Pro','🎞️','¥168/月',  'https://www.adobe.com/products/premiere.html','both',4,'专业视频剪辑，Adobe订阅，学习成本高',         undefined,         168,  0),
  davinci:     t('DaVinci Resolve','✂️','免费',  'https://www.blackmagicdesign.com/products/davinciresolve','both',4,'专业剪辑，免费版功能完整，学习曲线陡', undefined, 0, 0),
  ae:          t('After Effects','✨','¥168/月',  'https://www.adobe.com/products/aftereffects.html','both',5,'专业特效合成，需要扎实技术基础',            undefined,         168,  0),
  ps:          t('Photoshop AI','🖌️','¥168/月',  'https://www.adobe.com/products/photoshop.html','both',4,'行业标准修图工具，有AI功能，订阅制',           'adobe-firefly',   168,  0),
  wenxinyige:  t('文心一格',  '🎨', '免费',      'https://yige.baidu.com',                    'cn',   1, '百度出品，国内免费，中文提示词友好',          'wenxin-yige',     0,    0),
  tongyi:      t('通义万相',  '✨', '免费',      'https://tongyi.aliyun.com/wanxiang',         'cn',   1, '阿里出品，国内免费，效果稳定',               undefined,         0,    0),
  gaoding:     t('稿定设计',  '📐', '免费起',    'https://www.gaoding.com',                   'cn',   1, '国内设计工具，模板多，适合快速出图',          'gaoding',         0,    0),
  obsidian:    t('Obsidian',  '💎', '免费',      'https://obsidian.md',                       'both', 3, '双链笔记神器，本地存储，有学习成本',          undefined,         0,    0),
  yuque:       t('语雀',      '🦆', '免费',      'https://www.yuque.com',                     'cn',   1, '阿里旗下，国内知识管理工具，免费协作',        undefined,         0,    0),
  lsEditor:    t('135编辑器', '📝', '免费',      'https://www.135editor.com',                 'cn',   1, '公众号排版神器，模板一键套用',               undefined,         0,    0),
  mdnice:      t('Markdown Nice','✍️','免费',    'https://mdnice.com',                        'cn',   1, 'Markdown转公众号格式，开发者友好',           undefined,         0,    0),
  tome:        t('Tome',      '📖', '$20/月',    'https://tome.app',                          'vpn',  2, '叙事型演示文稿，适合路演，需梯子',            'tome',            0,    20),
  beautiful:   t('Beautiful.ai','💎','$12/月',   'https://www.beautiful.ai',                  'vpn',  2, 'PPT设计感强，自动对齐布局，需梯子',           undefined,         0,    12),
  volcTTS:     t('火山TTS',   '🔊', '按量付费',  'https://www.volcengine.com/product/tts',    'cn',   3, '字节系，API调用，需要一定技术能力',           'volcengine-tts',  0,    0),
  fastgpt:     t('FastGPT',   '⚡', '免费自部署','https://fastgpt.in',                        'both', 4, '私有化知识库，需要服务器，技术门槛较高',       'fastgpt',         0,    0),
  yixiaoer:   t('蚁小二',    '📱', '¥49/月',    'https://www.yixiaoer.cn',                   'cn',   2, '国内多平台分发工具，操作较简单',             undefined,         49,   0),
  comfyui:     t('ComfyUI',   '⚙️', '免费',      'https://github.com/comfyanonymous/ComfyUI', 'both', 5, '本地SD工作流，技术门槛最高，需要显卡+会配置', undefined,         0,    0),
  meitu:       t('美图秀秀AI','📸', '免费',      'https://www.meitu.com',                     'cn',   1, '国内免费，AI美化图片，一键操作',             undefined,         0,    0),
  etsy:        t('Etsy',      '🛒', '按单收费',  'https://www.etsy.com',                      'vpn',  2, '海外创意市场，卖AI绘画变现，需梯子+PayPal',   undefined,         0,    0),
  manus:       t('Manus',     '🤖', '邀请制',    'https://manus.im',                          'vpn',  3, '全球最强AI Agent，目前邀请制，需梯子',        'manus',           0,    0),
}

// ── 场景数据库 ─────────────────────────────────────────────
export const COMBOS_DB: Record<string, ToolCombo[]> = {

  // ══════════════════════════════════════════════════════
  // 短视频创作（video）
  // ══════════════════════════════════════════════════════
  video: [
    {
      id: 'v1', tier: 'mid', isRec: true,
      name: '豆包 + ElevenLabs + 剪映',
      tagline: '全流程贯通，30分钟出一条视频，基本免费',
      priceMin: 0, priceMax: 99,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '1小时',
      timePerOutput: '约30-45分钟/条',
      bestFor: '自媒体新手 / 想做中英双语口播的创作者',
      scenarios: ['短视频', '口播', '自媒体', '中英配音'],
      steps: [
        {
          phase: '脚本生成', conn: 'or',
          flowNote: '直接复制AI生成的文本到下一步配音工具',
          flowDifficulty: 'easy',
          tools: [TOOLS.doubao, TOOLS.deepseek],
        },
        {
          phase: '中转英 + AI配音', conn: 'or',
          flowNote: '粘贴脚本文本，选择音色，导出MP3音频文件',
          flowDifficulty: 'easy',
          tools: [TOOLS.elevenlabs, TOOLS.volcTTS],
        },
        {
          phase: '自动剪辑成片', conn: 'and',
          flowNote: '导入MP3音频，剪映AI自动对齐字幕，添加素材',
          flowDifficulty: 'medium',
          tools: [TOOLS.capcut],
        },
        {
          phase: '多平台分发', conn: 'or',
          flowNote: '导出MP4，一键上传到各平台',
          flowDifficulty: 'easy',
          tools: [TOOLS.yixiaoer],
        },
      ],
      pros: ['上手简单', '基本免费', '全流程打通', '中文支持好'],
      why: '豆包/DeepSeek 免费生成中文脚本，ElevenLabs 一键克隆声音并翻译英文配音，剪映AI自动对齐字幕。初次配置约1小时，之后每条视频30分钟内完成，月成本几乎为零，是刚起步自媒体人的最佳入门方案。',
    },
    {
      id: 'v2', tier: 'mid', isRec: false,
      name: 'Claude + HeyGen + Premiere',
      tagline: 'AI数字人口播，视频专业感更强',
      priceMin: 200, priceMax: 600,
      overallDifficulty: 3,
      netSummary: 'vpn',
      setupTime: '3-5小时',
      timePerOutput: '约2-3小时/条',
      bestFor: '有预算的品牌账号 / 想做IP化运营的创作者',
      scenarios: ['数字人', '口播', '品牌', '多语言'],
      steps: [
        {
          phase: '脚本 + 翻译', conn: 'and',
          flowNote: '让Claude生成脚本，并翻译成目标语言版本，复制文本',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35],
        },
        {
          phase: 'AI数字人生成', conn: 'and',
          flowNote: '粘贴脚本文本，选择数字人形象，渲染需10-30分钟，下载视频',
          flowDifficulty: 'medium',
          tools: [TOOLS.heygen],
        },
        {
          phase: '专业剪辑', conn: 'or',
          flowNote: '导入HeyGen视频，添加BGM/字幕/特效，导出成品',
          flowDifficulty: 'hard',
          tools: [TOOLS.premiere, TOOLS.davinci],
        },
        {
          phase: '数据监测', conn: 'and',
          flowNote: '发布后在飞瓜查看数据，分析爆款规律',
          flowDifficulty: 'easy',
          tools: [TOOLS.feigua],
        },
      ],
      pros: ['视频质感专业', 'AI数字人口播', '数据驱动', '真人声音克隆'],
      why: 'HeyGen 可克隆真人形象做无限口播视频，Claude 保障脚本质量，飞瓜数据分析爆款规律。适合想做IP化运营的博主，有明确的变现路径。月费较高，建议先验证内容方向再投入。',
    },
    {
      id: 'v3', tier: 'pro', isRec: false,
      name: 'Midjourney + Runway + GPT-4o',
      tagline: '纯AI生成画面，视觉差异化极强',
      priceMin: 800, priceMax: 2000,
      overallDifficulty: 4,
      netSummary: 'vpn',
      setupTime: '1-2天',
      timePerOutput: '约4-6小时/条',
      bestFor: 'AI创意团队 / 科技媒体 / 品牌宣传部门',
      scenarios: ['AI创意', '品牌宣传', '科技媒体', '无实拍'],
      steps: [
        {
          phase: 'AI图像素材', conn: 'and',
          flowNote: '编写Prompt生成分镜图，下载图片文件',
          flowDifficulty: 'medium',
          tools: [TOOLS.midjourney],
        },
        {
          phase: 'AI视频生成', conn: 'or',
          flowNote: '上传图片+添加运动描述，渲染15-30分钟，下载视频片段',
          flowDifficulty: 'medium',
          tools: [TOOLS.runway, TOOLS.kling],
        },
        {
          phase: '脚本 + 旁白', conn: 'and',
          flowNote: 'GPT写旁白文字，ElevenLabs生成配音MP3',
          flowDifficulty: 'easy',
          tools: [TOOLS.chatgpt, TOOLS.elevenlabs],
        },
        {
          phase: '后期合成', conn: 'and',
          flowNote: '将所有视频片段、配音、字幕在AE中合成，最复杂的一步',
          flowDifficulty: 'hard',
          tools: [TOOLS.ae],
        },
      ],
      pros: ['纯AI画面', '视觉差异化极强', '无需实拍', '科技感强'],
      why: '适合做AI创意内容、科技媒体、品牌宣传的专业团队。Midjourney 生成概念图，Runway/可灵 转化为视频，全程无需摄像机，视觉效果独特。工具多且均需梯子，建议有团队再考虑。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // 公众号运营（wechat）
  // ══════════════════════════════════════════════════════
  wechat: [
    {
      id: 'w1', tier: 'mid', isRec: true,
      name: 'Claude + 即梦AI + 135编辑器',
      tagline: '写稿配图排版一条龙，月成本不超200',
      priceMin: 20, priceMax: 200,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '30分钟',
      timePerOutput: '约1.5-2小时/篇',
      bestFor: '公众号创作者 / 企业新媒体运营',
      scenarios: ['公众号', '文章', '图文', '排版'],
      steps: [
        {
          phase: '选题 + 写稿', conn: 'or',
          flowNote: '输入主题关键词，生成完整文章，复制全文',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35, TOOLS.doubao],
        },
        {
          phase: 'AI配图生成', conn: 'or',
          flowNote: '输入图片描述，生成图片，下载JPG文件',
          flowDifficulty: 'easy',
          tools: [TOOLS.jimeng, TOOLS.midjourney],
        },
        {
          phase: '排版 + 发布', conn: 'or',
          flowNote: '粘贴文章到编辑器，套模板，复制HTML到公众号后台',
          flowDifficulty: 'easy',
          tools: [TOOLS.lsEditor, TOOLS.mdnice],
        },
      ],
      pros: ['写作质量高', 'AI配图美观', '一键排版', '成本可控'],
      why: 'Claude写的中文文章自然流畅无AI腔，即梦AI国内免费生图，135编辑器直接导入微信后台一键排版。熟练后一篇图文1.5小时搞定，月成本20-200元（有梯子用Claude），是公众号运营的最优性价比方案。',
    },
    {
      id: 'w2', tier: 'free', isRec: false,
      name: 'Kimi + 文心一格 + 秀米',
      tagline: '零成本全免费，国内工具全程可用',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '15分钟',
      timePerOutput: '约2小时/篇',
      bestFor: '公众号新手 / 不想付费的个人创作者',
      scenarios: ['公众号', '免费', '新手', '国内'],
      steps: [
        {
          phase: '写稿 + 润色', conn: 'and',
          flowNote: '输入主题让Kimi写稿，也可上传参考资料让它总结',
          flowDifficulty: 'easy',
          tools: [TOOLS.kimi],
        },
        {
          phase: 'AI配图', conn: 'and',
          flowNote: '输入中文描述生成图片，下载保存',
          flowDifficulty: 'easy',
          tools: [TOOLS.wenxinyige],
        },
        {
          phase: '排版发布', conn: 'and',
          flowNote: '在秀米选模板，粘贴文字，插入图片，复制到公众号',
          flowDifficulty: 'easy',
          tools: [
            t('秀米', '✨', '免费', 'https://xiumi.us', 'cn', 1, '公众号排版神器，模板丰富'),
          ],
        },
      ],
      pros: ['完全免费', '无需翻墙', '中文体验好', '上手简单'],
      why: '刚开始运营公众号、不想花钱试水的创作者的最佳起点。Kimi 长文处理能力强，文心一格国内免费生图，秀米是公众号排版神器。零成本跑通完整工作流，方向验证后再升级工具。',
    },
    {
      id: 'w3', tier: 'pro', isRec: false,
      name: 'GPT-4o + DALL-E 3 + Notion AI',
      tagline: '内容质量顶级，适合有调性的品牌号',
      priceMin: 300, priceMax: 600,
      overallDifficulty: 3,
      netSummary: 'vpn',
      setupTime: '2小时',
      timePerOutput: '约2-3小时/篇',
      bestFor: '品牌公众号 / 追求内容调性的企业账号',
      scenarios: ['品牌', '高质量', '内容管理', '团队协作'],
      steps: [
        {
          phase: '选题策划', conn: 'and',
          flowNote: '联网搜索热门话题，输出话题分析报告',
          flowDifficulty: 'easy',
          tools: [TOOLS.perplexity],
        },
        {
          phase: '文章创作', conn: 'and',
          flowNote: '输入选题和目标人群，GPT-4o生成高质量长文',
          flowDifficulty: 'easy',
          tools: [TOOLS.chatgpt],
        },
        {
          phase: '配图生成', conn: 'and',
          flowNote: 'ChatGPT内直接生成DALL-E图片，下载使用',
          flowDifficulty: 'easy',
          tools: [
            t('DALL-E 3', '🖼️', '含在ChatGPT', 'https://chat.openai.com', 'vpn', 1, '集成在ChatGPT内，无需额外订阅'),
          ],
        },
        {
          phase: '内容管理', conn: 'and',
          flowNote: '将文章存入Notion，用AI整理内容日历',
          flowDifficulty: 'medium',
          tools: [TOOLS.notion],
        },
      ],
      pros: ['内容质量顶级', '图文风格统一', '内容管理完善', '适合品牌号'],
      why: '追求内容调性和品牌一致性的公众号首选。Perplexity 联网找热门选题，GPT-4o 生成高质量内容，DALL-E 3 确保图片风格统一，Notion AI 管理内容日历。适合已有稳定读者群、想精细化运营的账号。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // 跨境电商（ecommerce）
  // ══════════════════════════════════════════════════════
  ecommerce: [
    {
      id: 'e1', tier: 'mid', isRec: true,
      name: 'DeepSeek + Helium 10 + Tidio',
      tagline: '选品+翻译+客服全自动，ROI极高',
      priceMin: 50, priceMax: 300,
      overallDifficulty: 3,
      netSummary: 'vpn',
      setupTime: '3-5小时',
      timePerOutput: '节省60%日常操作时间',
      bestFor: '亚马逊卖家 / 速卖通卖家',
      scenarios: ['亚马逊', '选品', '翻译', '客服'],
      steps: [
        {
          phase: '市场选品分析', conn: 'and',
          flowNote: '在Helium10分析关键词和竞品，导出数据表格',
          flowDifficulty: 'medium',
          tools: [TOOLS.helium10],
        },
        {
          phase: '产品描述翻译', conn: 'or',
          flowNote: '粘贴中文产品信息，生成英文listing文案',
          flowDifficulty: 'easy',
          tools: [TOOLS.deepseek, TOOLS.chatgpt],
        },
        {
          phase: 'AI智能客服', conn: 'and',
          flowNote: '在网站嵌入Tidio，配置AI知识库，自动回复买家问题',
          flowDifficulty: 'medium',
          tools: [TOOLS.tidio],
        },
        {
          phase: '广告文案', conn: 'and',
          flowNote: '批量生成广告标题和描述，直接导入广告后台',
          flowDifficulty: 'easy',
          tools: [TOOLS.copyai],
        },
      ],
      pros: ['选品数据精准', '翻译质量高', '24小时客服', 'ROI高'],
      why: 'Helium 10 是亚马逊卖家必备选品工具，DeepSeek 免费翻译产品描述效果媲美ChatGPT，Tidio AI 自动处理80%客服问题，Copy.ai 批量生成广告文案。注意Helium10和Tidio均需梯子。',
    },
    {
      id: 'e2', tier: 'free', isRec: false,
      name: 'DeepSeek + 豆包 + 国内免费工具',
      tagline: '零成本入门，适合刚起步的跨境卖家',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '30分钟',
      timePerOutput: '省去50%文案撰写时间',
      bestFor: '跨境电商新手 / 验证选品阶段的卖家',
      scenarios: ['入门', '免费', '翻译', '文案'],
      steps: [
        {
          phase: '产品分析 + 文案', conn: 'and',
          flowNote: '输入产品信息，DeepSeek生成中英文对照产品描述',
          flowDifficulty: 'easy',
          tools: [TOOLS.deepseek],
        },
        {
          phase: '批量翻译', conn: 'and',
          flowNote: '将产品标题列表粘贴给豆包，一次性翻译多个',
          flowDifficulty: 'easy',
          tools: [TOOLS.doubao],
        },
        {
          phase: '竞品评论分析', conn: 'and',
          flowNote: '复制竞品评论粘贴给Kimi，让它总结用户痛点和好评原因',
          flowDifficulty: 'easy',
          tools: [TOOLS.kimi],
        },
      ],
      pros: ['完全免费', '国内直接用', '无需注册', '上手快'],
      why: '预算有限的跨境新手最佳入门方案。DeepSeek 翻译质量媲美ChatGPT，豆包处理批量文案，Kimi 分析竞品买家评论找用户痛点。零成本验证选品，找到方向再升级工具。',
    },
    {
      id: 'e3', tier: 'pro', isRec: false,
      name: 'ChatGPT + Shopify + Klaviyo',
      tagline: '独立站全套AI自动化，成熟卖家升级方案',
      priceMin: 500, priceMax: 1500,
      overallDifficulty: 4,
      netSummary: 'vpn',
      setupTime: '1-2周',
      timePerOutput: '体系建立后高度自动化',
      bestFor: '有稳定销量的独立站卖家 / 品牌化运营团队',
      scenarios: ['独立站', '邮件营销', '广告', '品牌化'],
      steps: [
        {
          phase: '内容营销', conn: 'and',
          flowNote: '批量生成产品页文案、博客文章、社媒内容',
          flowDifficulty: 'easy',
          tools: [TOOLS.chatgpt],
        },
        {
          phase: '独立站建设', conn: 'and',
          flowNote: '建站、选主题、配置支付，初次设置耗时最多',
          flowDifficulty: 'medium',
          tools: [TOOLS.shopify],
        },
        {
          phase: '邮件营销自动化', conn: 'and',
          flowNote: '配置邮件序列，与Shopify连接，触发式自动发送',
          flowDifficulty: 'hard',
          tools: [TOOLS.klaviyo],
        },
        {
          phase: '广告素材', conn: 'and',
          flowNote: '上传产品信息，AI自动生成多尺寸广告图',
          flowDifficulty: 'medium',
          tools: [TOOLS.adcreative],
        },
      ],
      pros: ['全链路自动化', '邮件营销精准', '广告ROI高', '品牌化完善'],
      why: '有稳定销量、想做品牌化的成熟跨境卖家。Shopify+Klaviyo是独立站标配，ChatGPT批量生产内容，AdCreative.ai自动生成高转化率广告素材。初始搭建复杂，运行后高度自动化。所有工具均需梯子。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // 独立开发（dev）
  // ══════════════════════════════════════════════════════
  dev: [
    {
      id: 'd1', tier: 'mid', isRec: true,
      name: 'Cursor + Claude + Vercel',
      tagline: 'AI辅助全栈开发，效率提升3倍',
      priceMin: 40, priceMax: 150,
      overallDifficulty: 3,
      netSummary: 'both',
      setupTime: '2小时',
      timePerOutput: '开发效率提升3倍',
      bestFor: '有编程基础的独立开发者 / SaaS创业者',
      scenarios: ['全栈开发', 'MVP', 'SaaS', '独立开发'],
      steps: [
        {
          phase: '需求分析 + 架构', conn: 'and',
          flowNote: '描述产品需求，Claude输出PRD和数据库设计，复制到Cursor',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35],
        },
        {
          phase: 'AI辅助编码', conn: 'and',
          flowNote: 'Cursor已集成Claude，在IDE中直接对话写代码，Tab补全',
          flowDifficulty: 'medium',
          tools: [TOOLS.cursor],
        },
        {
          phase: '代码审查 + 测试', conn: 'or',
          flowNote: '代码粘贴给AI让它生成测试用例或检查Bug',
          flowDifficulty: 'easy',
          tools: [TOOLS.copilot, TOOLS.codeium],
        },
        {
          phase: '一键部署上线', conn: 'and',
          flowNote: '连接GitHub仓库，推送代码自动部署，几分钟上线',
          flowDifficulty: 'easy',
          tools: [TOOLS.vercel],
        },
      ],
      pros: ['编码速度提升3倍', '一键部署', '成本极低', '全栈覆盖'],
      why: 'Cursor是目前最好的AI编程IDE，Claude处理复杂逻辑和架构设计，Vercel一键部署。这套组合让独立开发者生产效率提升3倍，¥150/月可以跑通一个MVP。Cursor和Vercel国内均可访问，Claude需梯子。',
    },
    {
      id: 'd2', tier: 'free', isRec: false,
      name: 'VS Code + Codeium + GitHub',
      tagline: '全免费开发工作流，学生和业余开发者首选',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 2,
      netSummary: 'both',
      setupTime: '1小时',
      timePerOutput: '编码效率提升约1.5倍',
      bestFor: '在校学生 / 编程学习者 / 业余开发者',
      scenarios: ['学习', '开源', '免费', '基础开发'],
      steps: [
        {
          phase: 'AI辅助编码', conn: 'and',
          flowNote: 'VS Code安装Codeium插件，实时AI补全代码',
          flowDifficulty: 'easy',
          tools: [TOOLS.codeium],
        },
        {
          phase: '代码托管', conn: 'and',
          flowNote: 'git push推送代码，GitHub Actions自动触发CI/CD',
          flowDifficulty: 'medium',
          tools: [
            t('GitHub', '🐙', '免费', 'https://github.com', 'both', 2, '国内访问有时较慢，建议用镜像'),
          ],
        },
        {
          phase: '自动化部署', conn: 'or',
          flowNote: '代码推送后自动部署，Vercel更简单，Actions更灵活',
          flowDifficulty: 'medium',
          tools: [
            t('GitHub Actions', '⚙️', '免费', 'https://github.com/features/actions', 'both', 3, '免费CI/CD，需要写yaml配置'),
            TOOLS.vercel,
          ],
        },
      ],
      pros: ['完全免费', '上手门槛低', 'CI/CD自动化', '社区资源丰富'],
      why: '学生、业余开发者或刚入门的独立开发者最佳起点。Codeium免费AI补全媲美Copilot，GitHub Actions自动化CI/CD，全套免费跑通完整开发流程。所有工具国内均可访问（GitHub偶有问题）。',
    },
    {
      id: 'd3', tier: 'pro', isRec: false,
      name: 'Bolt.new + Claude + Supabase',
      tagline: '无需本地环境，浏览器全栈开发快速上线',
      priceMin: 50, priceMax: 200,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '30分钟',
      timePerOutput: '一个周末可上线MVP',
      bestFor: '非技术创始人 / 快速验证想法的产品人',
      scenarios: ['快速原型', '无环境', '全栈', '非技术创始人'],
      steps: [
        {
          phase: '全栈应用生成', conn: 'and',
          flowNote: '用自然语言描述产品，Bolt直接生成完整代码并预览',
          flowDifficulty: 'easy',
          tools: [TOOLS.boltNew],
        },
        {
          phase: '复杂逻辑辅助', conn: 'and',
          flowNote: '遇到复杂业务逻辑，复制代码给Claude分析修改',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35],
        },
        {
          phase: '数据库 + 后端', conn: 'and',
          flowNote: 'Supabase提供免费PostgreSQL，Bolt可一键集成',
          flowDifficulty: 'medium',
          tools: [TOOLS.supabase],
        },
        {
          phase: '部署', conn: 'and',
          flowNote: 'Bolt内直接部署到Vercel，一键操作',
          flowDifficulty: 'easy',
          tools: [TOOLS.vercel],
        },
      ],
      pros: ['无需本地环境', '全栈能力', '快速验证想法', '非技术可上手'],
      why: '非技术创始人验证想法的最快路径。Bolt.new在浏览器里生成完整应用代码，Claude处理复杂业务逻辑，Supabase提供免费数据库，Vercel一键部署。Bolt需梯子，Supabase和Vercel国内可访问。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // AI绘画变现（painting）
  // ══════════════════════════════════════════════════════
  painting: [
    {
      id: 'p1', tier: 'mid', isRec: true,
      name: '即梦AI + Midjourney + Canva',
      tagline: '生图精修商用一条龙，月入过万可实现',
      priceMin: 10, priceMax: 100,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '1-2天（学习Midjourney提示词）',
      timePerOutput: '批量出图约2-3小时',
      bestFor: '想通过AI绘画变现的创作者 / 设计需求方',
      scenarios: ['绘画', '变现', '商业', '设计'],
      steps: [
        {
          phase: '快速批量出图', conn: 'or',
          flowNote: '用中文描述生成图片，国内免费工具先批量探索方向',
          flowDifficulty: 'easy',
          tools: [TOOLS.jimeng, TOOLS.wenxinyige],
        },
        {
          phase: '高质量商业图', conn: 'and',
          flowNote: '确定方向后切换Midjourney，英文Prompt生成精品图，下载PNG',
          flowDifficulty: 'medium',
          tools: [TOOLS.midjourney],
        },
        {
          phase: '后期排版商用', conn: 'and',
          flowNote: '导入Canva，套商用模板，添加文字，导出成品',
          flowDifficulty: 'easy',
          tools: [TOOLS.canva],
        },
        {
          phase: '接单平台', conn: 'or',
          flowNote: '上传作品到平台销售，Etsy面向海外，稿定面向国内',
          flowDifficulty: 'easy',
          tools: [TOOLS.gaoding, TOOLS.etsy],
        },
      ],
      pros: ['出图速度快', '商业授权清晰', '变现路径明确', '成本极低'],
      why: '即梦AI免费积累素材和探索方向，Midjourney生成高质量商业图，Canva快速排版做成成品，Etsy卖给海外客户。已有大量人用这套工具实现月入过万。Midjourney和Etsy需梯子。',
    },
    {
      id: 'p2', tier: 'free', isRec: false,
      name: '国内免费AI绘画三件套',
      tagline: '零成本体验AI绘画，新手入门首选',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '10分钟',
      timePerOutput: '随时出图',
      bestFor: '刚接触AI绘画的新手 / 不确定是否继续的用户',
      scenarios: ['入门', '免费', '国内', '个人'],
      steps: [
        {
          phase: '文生图', conn: 'or',
          flowNote: '输入中文描述即可出图，三个工具各有特色风格',
          flowDifficulty: 'easy',
          tools: [TOOLS.jimeng, TOOLS.wenxinyige, TOOLS.tongyi],
        },
        {
          phase: '图片处理', conn: 'and',
          flowNote: '下载图片，导入美图秀秀做简单修饰',
          flowDifficulty: 'easy',
          tools: [TOOLS.meitu],
        },
      ],
      pros: ['完全免费', '国内直连', '中文提示词', '无需科学上网'],
      why: '刚开始接触AI绘画、不确定是否继续的新手。即梦AI、文心一格、通义万相都是国内免费工具，中文提示词效果好，零门槛体验AI绘画乐趣，找到感觉后再升级Midjourney。',
    },
    {
      id: 'p3', tier: 'pro', isRec: false,
      name: 'Midjourney + Stable Diffusion + Photoshop AI',
      tagline: '专业级工作流，支持定制模型和批量商业出图',
      priceMin: 200, priceMax: 800,
      overallDifficulty: 5,
      netSummary: 'vpn',
      setupTime: '1-2周（需学SD和ComfyUI）',
      timePerOutput: '本地批量出图速度快',
      bestFor: '有技术背景的专业AI绘画商业服务者',
      scenarios: ['专业', '定制模型', '批量', '商业服务'],
      steps: [
        {
          phase: '高质量概念图', conn: 'and',
          flowNote: '确定风格方向，生成精品概念图',
          flowDifficulty: 'medium',
          tools: [TOOLS.midjourney],
        },
        {
          phase: '本地定制 + 批量', conn: 'and',
          flowNote: '本地部署SD，训练LoRA模型，ComfyUI搭建批量工作流',
          flowDifficulty: 'hard',
          tools: [TOOLS.sd, TOOLS.comfyui],
        },
        {
          phase: '专业后期', conn: 'and',
          flowNote: '精修细节、抠图、合成，PS AI生成填充',
          flowDifficulty: 'hard',
          tools: [TOOLS.ps],
        },
      ],
      pros: ['完全可控', '支持LoRA微调', '批量商业出图', '专业服务'],
      why: '有技术基础、想做专业AI绘画商业服务的创作者。SD+ComfyUI需要较强技术能力且需要N卡，Midjourney和PS均需梯子或订阅。适合已经在做AI绘画、想升级专业度的人。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // 播客制作（podcast）
  // ══════════════════════════════════════════════════════
  podcast: [
    {
      id: 'pk1', tier: 'mid', isRec: true,
      name: 'Descript + Claude + 小宇宙',
      tagline: '录音剪辑字幕一体化，国内外双平台分发',
      priceMin: 20, priceMax: 200,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '2小时',
      timePerOutput: '约2小时/期（含录制）',
      bestFor: '中文播客创作者 / 想进军海外的播客主',
      scenarios: ['播客', '录音', '字幕', '分发'],
      steps: [
        {
          phase: '节目策划 + 脚本', conn: 'and',
          flowNote: 'Claude策划节目结构、嘉宾问题列表，复制到文档',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35],
        },
        {
          phase: '录音 + 降噪 + 剪辑', conn: 'and',
          flowNote: '录制完成后，Descript自动转写文字，像编辑文档一样剪辑',
          flowDifficulty: 'medium',
          tools: [TOOLS.descript],
        },
        {
          phase: '国内平台发布', conn: 'and',
          flowNote: '导出MP3，上传到小宇宙，填写节目信息发布',
          flowDifficulty: 'easy',
          tools: [TOOLS.ximalaya],
        },
      ],
      pros: ['一体化工作流', '自动字幕', '国内外兼顾', '操作简单'],
      why: 'Descript是播客制作神器，录音、降噪、转写字幕、剪辑一体化，Claude策划节目脚本，小宇宙是国内最大播客平台流量好。Descript需梯子，小宇宙国内直连，月成本20-200元。',
    },
    {
      id: 'pk2', tier: 'free', isRec: false,
      name: 'Audacity + 讯飞听见 + 小宇宙',
      tagline: '全免费国内播客工具，零门槛起步',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 2,
      netSummary: 'cn',
      setupTime: '1小时（学习Audacity基础操作）',
      timePerOutput: '约3小时/期',
      bestFor: '预算为零的播客新手 / 国内中文播客创作者',
      scenarios: ['国内', '免费', '中文播客', '新手'],
      steps: [
        {
          phase: '录音 + 剪辑', conn: 'and',
          flowNote: '下载安装Audacity，录音后剪掉口误和停顿，导出MP3',
          flowDifficulty: 'medium',
          tools: [TOOLS.audacity],
        },
        {
          phase: 'AI转写字幕', conn: 'and',
          flowNote: '上传MP3到讯飞听见，自动转写，下载文字稿',
          flowDifficulty: 'easy',
          tools: [TOOLS.iflytek],
        },
        {
          phase: '国内平台发布', conn: 'and',
          flowNote: '在小宇宙上传音频，配封面图，发布节目',
          flowDifficulty: 'easy',
          tools: [TOOLS.ximalaya],
        },
      ],
      pros: ['完全免费', '国内平台', '中文转写准', '无需翻墙'],
      why: '想做国内播客的创作者最低门槛方案。Audacity是专业级免费录音软件，讯飞听见中文转写准确率95%+，小宇宙是国内最大播客平台，零成本起步测试内容方向。',
    },
    {
      id: 'pk3', tier: 'pro', isRec: false,
      name: 'Adobe Audition + ElevenLabs + Buzzsprout',
      tagline: '专业音质国际发布，做双语播客首选',
      priceMin: 200, priceMax: 500,
      overallDifficulty: 4,
      netSummary: 'vpn',
      setupTime: '3-5天（学习AU操作）',
      timePerOutput: '约4-5小时/期',
      bestFor: '面向国际受众的双语播客创作者 / 品牌播客',
      scenarios: ['专业', '国际', '双语', '品牌播客'],
      steps: [
        {
          phase: '专业录音混音', conn: 'and',
          flowNote: '多轨录制、均衡器调整、降噪处理，导出高质量WAV',
          flowDifficulty: 'hard',
          tools: [TOOLS.adobeAud],
        },
        {
          phase: 'AI语音克隆翻译', conn: 'and',
          flowNote: '上传原声音频让ElevenLabs克隆，生成多语言版本音频',
          flowDifficulty: 'medium',
          tools: [TOOLS.elevenlabs],
        },
        {
          phase: '国际平台发布', conn: 'and',
          flowNote: 'Buzzsprout自动分发到Spotify、Apple Podcasts等20+平台',
          flowDifficulty: 'easy',
          tools: [TOOLS.buzzsprout],
        },
      ],
      pros: ['专业音质', 'AI声音克隆', '国际受众', '双语内容'],
      why: '做高质量英文或双语播客、面向国际受众的创作者。Adobe Audition专业混音，ElevenLabs克隆你的声音做多语言版本，Buzzsprout自动分发。所有工具均需梯子，Adobe订阅费用较高。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // AI写作变现（writing）
  // ══════════════════════════════════════════════════════
  writing: [
    {
      id: 'wr1', tier: 'mid', isRec: true,
      name: 'Claude + 写作猫 + 秘塔AI搜索',
      tagline: 'AI辅助高质量写作，产量提升5倍',
      priceMin: 20, priceMax: 200,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '30分钟',
      timePerOutput: '约30-45分钟/篇（原来2-3小时）',
      bestFor: '自由撰稿人 / 新媒体运营 / 内容创作者',
      scenarios: ['写作', '内容', '自媒体', '新媒体'],
      steps: [
        {
          phase: '选题 + 素材收集', conn: 'and',
          flowNote: '秘塔无广告搜索资料，整理成大纲复制给AI',
          flowDifficulty: 'easy',
          tools: [TOOLS.metaso],
        },
        {
          phase: '初稿生成', conn: 'or',
          flowNote: '输入主题+大纲+目标读者，生成完整文章初稿',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35, TOOLS.doubao],
        },
        {
          phase: '校对 + 优化', conn: 'and',
          flowNote: '粘贴全文，写作猫检查语法、优化表达、降低AI味',
          flowDifficulty: 'easy',
          tools: [TOOLS.xiezuomao],
        },
        {
          phase: '分发变现', conn: 'or',
          flowNote: '发布到各平台，公众号广告收益最高',
          flowDifficulty: 'easy',
          tools: [
            t('公众号', '📱', '免费', 'https://mp.weixin.qq.com', 'cn', 1, '广告收益分成，需要粉丝积累'),
            t('百家号', '🔷', '免费', 'https://baijiahao.baidu.com', 'cn', 1, '百度流量大，收益稳定'),
          ],
        },
      ],
      pros: ['写作质量高', '产量提升5倍', '校对专业', '成本低'],
      why: '秘塔搜索无广告找素材，Claude生成高质量初稿（中文无AI腔），写作猫专业校对和降重，发布到多平台获得流量变现。这套工具让单人写作产量提升5倍。有梯子用Claude，没有梯子用豆包。',
    },
    {
      id: 'wr2', tier: 'free', isRec: false,
      name: 'DeepSeek + Kimi + 免费平台',
      tagline: '零成本AI写作，学习写作的最佳起点',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '10分钟',
      timePerOutput: '约1小时/篇',
      bestFor: '写作初学者 / 零预算的内容创作者',
      scenarios: ['免费', '新手', '学习', '个人'],
      steps: [
        {
          phase: '内容研究', conn: 'and',
          flowNote: '上传文章/PDF给Kimi，让它提炼核心观点',
          flowDifficulty: 'easy',
          tools: [TOOLS.kimi],
        },
        {
          phase: '写作生成', conn: 'and',
          flowNote: '输入主题和风格要求，DeepSeek生成文章初稿',
          flowDifficulty: 'easy',
          tools: [TOOLS.deepseek],
        },
        {
          phase: '发布平台', conn: 'or',
          flowNote: '直接在平台发布，知乎和小红书流量更好',
          flowDifficulty: 'easy',
          tools: [
            t('微信公众号', '📱', '免费', 'https://mp.weixin.qq.com', 'cn', 1),
            t('知乎', '🔵', '免费', 'https://www.zhihu.com', 'cn', 1, '专业内容流量好'),
            t('小红书', '📕', '免费', 'https://www.xiaohongshu.com', 'cn', 1, '年轻用户为主'),
          ],
        },
      ],
      pros: ['完全免费', '国内直连', '无学习门槛', '平台流量大'],
      why: '刚开始学习AI辅助写作、零预算的新手。Kimi研究资料，DeepSeek写初稿，免费发布到微信、知乎、小红书。先建立内容感觉，找到方向后再投入付费工具。',
    },
    {
      id: 'wr3', tier: 'pro', isRec: false,
      name: 'GPT-4o + Jasper + Grammarly',
      tagline: '英文写作专业级，适合出海内容',
      priceMin: 100, priceMax: 400,
      overallDifficulty: 3,
      netSummary: 'vpn',
      setupTime: '1小时',
      timePerOutput: '约1小时/篇英文内容',
      bestFor: '做英文内容营销的出海团队 / 外贸企业',
      scenarios: ['英文', '出海', '营销', 'SEO'],
      steps: [
        {
          phase: '内容策略', conn: 'and',
          flowNote: 'Perplexity联网研究英文市场热点和竞争对手',
          flowDifficulty: 'easy',
          tools: [TOOLS.perplexity],
        },
        {
          phase: '英文写作', conn: 'or',
          flowNote: '输入中文意图，生成专业英文内容',
          flowDifficulty: 'easy',
          tools: [TOOLS.chatgpt,
            t('Jasper', '📝', '$39/月', 'https://www.jasper.ai', 'vpn', 2, '专为营销内容设计，模板丰富', 'jasper', 0, 39),
          ],
        },
        {
          phase: '英文校对优化', conn: 'and',
          flowNote: '浏览器插件实时检查，或粘贴全文批量校对',
          flowDifficulty: 'easy',
          tools: [TOOLS.grammarly],
        },
      ],
      pros: ['英文质量专业', 'SEO友好', '营销转化高', '出海必备'],
      why: '做英文内容、出海营销的创作者。Perplexity研究英文市场，GPT-4o/Jasper生成专业英文内容，Grammarly确保语法无误。所有工具均需梯子。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // PPT制作（ppt）
  // ══════════════════════════════════════════════════════
  ppt: [
    {
      id: 'pp1', tier: 'mid', isRec: true,
      name: 'Claude + Gamma + Canva',
      tagline: '一键生成设计精美PPT，30分钟搞定',
      priceMin: 8, priceMax: 150,
      overallDifficulty: 1,
      netSummary: 'vpn',
      setupTime: '10分钟',
      timePerOutput: '约30分钟/份PPT',
      bestFor: '需要快速出PPT的职场人 / 学生 / 创业者',
      scenarios: ['PPT', '演示', '商务', '快速制作'],
      steps: [
        {
          phase: '内容规划', conn: 'and',
          flowNote: 'Claude输出PPT大纲和每页要点，复制文字内容',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35],
        },
        {
          phase: 'AI生成PPT', conn: 'and',
          flowNote: '粘贴大纲到Gamma，选模板，AI自动生成完整幻灯片',
          flowDifficulty: 'easy',
          tools: [TOOLS.gamma],
        },
        {
          phase: '配图补充', conn: 'and',
          flowNote: '在Canva找补充图片素材，下载插入PPT',
          flowDifficulty: 'easy',
          tools: [TOOLS.canva],
        },
      ],
      pros: ['设计感极强', '30分钟搞定', '操作简单', '多格式导出'],
      why: 'Claude先规划内容结构，Gamma AI自动生成设计精美的PPT，Canva补充配图素材。30分钟可以做出比手工做一天还好看的PPT。注意Gamma需梯子，国内可用AiPPT替代。',
    },
    {
      id: 'pp2', tier: 'free', isRec: false,
      name: 'AiPPT + WPS AI + 豆包',
      tagline: '国内全免费PPT制作，无需翻墙',
      priceMin: 0, priceMax: 35,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '5分钟',
      timePerOutput: '约20分钟/份PPT',
      bestFor: '国内用户 / 无法访问Gamma的用户 / 学生',
      scenarios: ['PPT', '国内', '免费', '学生'],
      steps: [
        {
          phase: 'AI生成PPT', conn: 'or',
          flowNote: '输入主题，AI一键生成完整PPT，可选模板风格',
          flowDifficulty: 'easy',
          tools: [TOOLS.aippt, TOOLS.wpsai],
        },
        {
          phase: '内容润色', conn: 'and',
          flowNote: '将每页要点粘贴给豆包，让它改写得更有表现力',
          flowDifficulty: 'easy',
          tools: [TOOLS.doubao],
        },
      ],
      pros: ['国内直连', '基本免费', '操作简单', '中文模板多'],
      why: '国内用户无法访问Gamma时的最佳替代。AiPPT基础免费，WPS AI深度整合Office，豆包润色内容，整套国内直连，价格实惠，适合学生和基础商务场景。',
    },
    {
      id: 'pp3', tier: 'pro', isRec: false,
      name: 'Tome + Beautiful.ai + Midjourney',
      tagline: '投资人级别演示，讲故事视觉俱佳',
      priceMin: 50, priceMax: 200,
      overallDifficulty: 3,
      netSummary: 'vpn',
      setupTime: '2-3小时',
      timePerOutput: '约2-4小时/份（高质量）',
      bestFor: '融资路演的创业者 / 品牌演示需求方',
      scenarios: ['路演', '投资人', '品牌', '故事'],
      steps: [
        {
          phase: '叙事型PPT生成', conn: 'or',
          flowNote: '输入商业故事，生成流畅的叙事型演示文稿',
          flowDifficulty: 'easy',
          tools: [TOOLS.tome, TOOLS.beautiful],
        },
        {
          phase: '高质量图片', conn: 'and',
          flowNote: '生成震撼的视觉素材，下载并插入PPT',
          flowDifficulty: 'medium',
          tools: [TOOLS.midjourney],
        },
        {
          phase: '内容打磨', conn: 'and',
          flowNote: '让Claude审阅每页叙述逻辑，优化表达',
          flowDifficulty: 'easy',
          tools: [TOOLS.claude35],
        },
      ],
      pros: ['叙事感强', '视觉冲击大', '投资人喜欢', '动效丰富'],
      why: '做融资路演、品牌演示的创业者。Tome生成叙事型演示，Midjourney提供震撼的视觉素材，Claude打磨每一页的叙述逻辑。所有工具均需梯子，月费较高但效果顶级。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // AI音乐创作（music）
  // ══════════════════════════════════════════════════════
  music: [
    {
      id: 'mu1', tier: 'mid', isRec: true,
      name: 'Suno + ElevenLabs + 剪映',
      tagline: '从歌词到带配乐视频，全流程AI音乐创作',
      priceMin: 13, priceMax: 50,
      overallDifficulty: 2,
      netSummary: 'vpn',
      setupTime: '30分钟',
      timePerOutput: '约30分钟/首（含MV）',
      bestFor: '想做AI音乐内容的创作者 / 音乐爱好者',
      scenarios: ['音乐', '歌曲', '配乐', '视频'],
      steps: [
        {
          phase: '生成完整歌曲', conn: 'or',
          flowNote: '输入歌曲风格和歌词，AI生成带人声的完整歌曲，下载MP3',
          flowDifficulty: 'easy',
          tools: [TOOLS.suno, TOOLS.udio],
        },
        {
          phase: '声音克隆演唱', conn: 'and',
          flowNote: '上传你的声音样本，ElevenLabs生成你声音演唱的版本',
          flowDifficulty: 'medium',
          tools: [TOOLS.elevenlabs],
        },
        {
          phase: '制作音乐MV', conn: 'and',
          flowNote: '导入音频到剪映，配合AI生成的图片素材制作MV',
          flowDifficulty: 'medium',
          tools: [TOOLS.capcut],
        },
      ],
      pros: ['30分钟出完整歌曲', '声音可定制', '可做MV', '成本极低'],
      why: 'Suno/Udio生成带人声的完整歌曲，ElevenLabs替换成你的声音，剪映制作成MV发布到抖音。整个流程一个人30分钟完成，月成本不超50元。Suno和ElevenLabs均需梯子。',
    },
    {
      id: 'mu2', tier: 'free', isRec: false,
      name: 'Suno免费版 + 即梦AI',
      tagline: '完全免费体验AI音乐创作',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'vpn',
      setupTime: '10分钟',
      timePerOutput: '10分钟/首（受免费额度限制）',
      bestFor: '对AI音乐感兴趣但不想付费的用户',
      scenarios: ['音乐', '免费', '体验', '新手'],
      steps: [
        {
          phase: '生成歌曲', conn: 'and',
          flowNote: '免费版每天50积分，可生成4-5首歌，下载MP3',
          flowDifficulty: 'easy',
          tools: [TOOLS.suno],
        },
        {
          phase: 'MV配图', conn: 'and',
          flowNote: '即梦AI生成音乐风格的图片，剪映拼成MV',
          flowDifficulty: 'easy',
          tools: [TOOLS.jimeng],
        },
      ],
      pros: ['完全免费', '无需技术', '快速出成果', '趣味强'],
      why: '对AI音乐感兴趣但不想付费的用户。Suno免费版每天50积分可以生成几首歌，即梦AI配上MV画面，可以分享到社媒。注意Suno需梯子，即梦AI国内直连。',
    },
    {
      id: 'mu3', tier: 'pro', isRec: false,
      name: 'Udio Pro + Runway + Adobe Audition',
      tagline: '专业AI音乐制作，用于商业项目',
      priceMin: 200, priceMax: 600,
      overallDifficulty: 4,
      netSummary: 'vpn',
      setupTime: '1-2天',
      timePerOutput: '约3-5小时/首（商业级）',
      bestFor: '需要为商业项目制作AI音乐的专业人士',
      scenarios: ['专业', '商业', '广告配乐', '游戏音乐'],
      steps: [
        {
          phase: '专业音乐生成', conn: 'and',
          flowNote: 'Udio Pro精细控制风格、节拍、乐器编排',
          flowDifficulty: 'medium',
          tools: [TOOLS.udio],
        },
        {
          phase: 'AI视频生成', conn: 'and',
          flowNote: '生成与音乐风格匹配的视觉内容',
          flowDifficulty: 'medium',
          tools: [TOOLS.runway],
        },
        {
          phase: '专业混音后期', conn: 'and',
          flowNote: '均衡器、压缩、母带处理，达到商业发行标准',
          flowDifficulty: 'hard',
          tools: [TOOLS.adobeAud],
        },
      ],
      pros: ['音质专业', '商业可授权', '视觉内容完整', '专业控制'],
      why: '需要为商业项目制作AI音乐的专业人士。Udio Pro提供精细风格控制和专业音质，Runway生成对应视觉内容，Adobe Audition专业混音，整套可用于广告、游戏、品牌配乐。所有工具均需梯子。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // 知识管理（knowledge）
  // ══════════════════════════════════════════════════════
  knowledge: [
    {
      id: 'kn1', tier: 'mid', isRec: true,
      name: 'Notion AI + Kimi + 秘塔搜索',
      tagline: 'AI辅助个人知识管理，学习效率倍增',
      priceMin: 20, priceMax: 100,
      overallDifficulty: 2,
      netSummary: 'both',
      setupTime: '1-2小时（搭建Notion结构）',
      timePerOutput: '日常使用学习效率提升3-5倍',
      bestFor: '知识工作者 / 在校学生 / 研究人员',
      scenarios: ['知识管理', '学习', '笔记', '研究'],
      steps: [
        {
          phase: '信息收集研究', conn: 'and',
          flowNote: '秘塔无广告搜索资料，复制核心内容',
          flowDifficulty: 'easy',
          tools: [TOOLS.metaso],
        },
        {
          phase: '长文档处理', conn: 'and',
          flowNote: '上传PDF/长文章给Kimi，让它总结要点和提炼洞察',
          flowDifficulty: 'easy',
          tools: [TOOLS.kimi],
        },
        {
          phase: '知识库整理', conn: 'and',
          flowNote: '粘贴内容到Notion，用AI自动整理分类和生成摘要',
          flowDifficulty: 'medium',
          tools: [TOOLS.notion],
        },
      ],
      pros: ['信息组织高效', '长文档处理强', '知识可检索', '协作方便'],
      why: '秘塔搜索无广告找资料，Kimi处理超长PDF和报告（免费），Notion AI整理成可检索的知识库。学习效率提升3-5倍。Notion偶有访问问题，建议备好梯子。',
    },
    {
      id: 'kn2', tier: 'free', isRec: false,
      name: 'Kimi + DeepSeek + 语雀',
      tagline: '全免费知识管理，国内工具全程可用',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '30分钟',
      timePerOutput: '零成本高效学习',
      bestFor: '预算有限的学生 / 国内知识工作者',
      scenarios: ['免费', '国内', '笔记', '学习'],
      steps: [
        {
          phase: 'AI阅读总结', conn: 'and',
          flowNote: '上传文件或粘贴长文，Kimi自动总结核心内容',
          flowDifficulty: 'easy',
          tools: [TOOLS.kimi],
        },
        {
          phase: 'AI问答分析', conn: 'and',
          flowNote: '针对学习内容向DeepSeek深度提问，梳理思路',
          flowDifficulty: 'easy',
          tools: [TOOLS.deepseek],
        },
        {
          phase: '知识整理存储', conn: 'and',
          flowNote: '将笔记整理到语雀，按主题分类，建立个人知识库',
          flowDifficulty: 'easy',
          tools: [TOOLS.yuque],
        },
      ],
      pros: ['完全免费', '国内直连', '中文支持好', '无学习成本'],
      why: '国内用户零成本搭建个人知识管理系统。Kimi阅读和总结长文档，DeepSeek深度分析问题，语雀整理笔记（阿里旗下免费协作文档），全套国内直连，无需翻墙。',
    },
    {
      id: 'kn3', tier: 'pro', isRec: false,
      name: 'Dify + Claude + Obsidian',
      tagline: '打造私有AI知识库，企业级知识管理',
      priceMin: 50, priceMax: 300,
      overallDifficulty: 4,
      netSummary: 'vpn',
      setupTime: '1-3天（服务器部署）',
      timePerOutput: '建立后知识调用效率极高',
      bestFor: '需要私有化AI知识库的企业或技术团队',
      scenarios: ['企业', '私有化', '知识库', 'RAG'],
      steps: [
        {
          phase: '私有知识库搭建', conn: 'and',
          flowNote: '服务器部署Dify，上传公司文档建立RAG知识库',
          flowDifficulty: 'hard',
          tools: [TOOLS.dify],
        },
        {
          phase: 'AI问答引擎', conn: 'and',
          flowNote: '配置Claude API为AI引擎，实现知识库智能问答',
          flowDifficulty: 'medium',
          tools: [TOOLS.claude35],
        },
        {
          phase: '个人笔记管理', conn: 'and',
          flowNote: 'Obsidian管理个人双链笔记，与Dify知识库互补',
          flowDifficulty: 'medium',
          tools: [TOOLS.obsidian],
        },
      ],
      pros: ['数据私有安全', '知识问答精准', '双链笔记', '可扩展'],
      why: '需要私有化AI知识库的团队或重度知识工作者。Dify部署私有知识库问答系统，Claude API提供最强AI能力，Obsidian管理个人双链笔记。Dify需服务器，Claude需梯子，技术门槛较高。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // 直播带货（livestream）
  // ══════════════════════════════════════════════════════
  livestream: [
    {
      id: 'ls1', tier: 'mid', isRec: true,
      name: '豆包 + 飞瓜数据 + 剪映',
      tagline: 'AI话术+数据选品+视频素材，直播效率翻倍',
      priceMin: 100, priceMax: 400,
      overallDifficulty: 2,
      netSummary: 'cn',
      setupTime: '1小时',
      timePerOutput: '数据驱动直播，转化率显著提升',
      bestFor: '有一定基础的直播带货主播 / 直播运营团队',
      scenarios: ['直播', '带货', '选品', '话术'],
      steps: [
        {
          phase: '选品数据分析', conn: 'and',
          flowNote: '飞瓜查看当前爆款品类和竞品数据，导出选品报告',
          flowDifficulty: 'medium',
          tools: [TOOLS.feigua],
        },
        {
          phase: 'AI直播话术生成', conn: 'and',
          flowNote: '输入商品信息和目标人群，豆包生成完整直播话术脚本',
          flowDifficulty: 'easy',
          tools: [TOOLS.doubao],
        },
        {
          phase: '预热短视频制作', conn: 'and',
          flowNote: '剪映快速剪辑预热视频，AI自动字幕，发布到主页引流',
          flowDifficulty: 'medium',
          tools: [TOOLS.capcut],
        },
        {
          phase: '直播数据复盘', conn: 'and',
          flowNote: '直播结束后在飞瓜查看GMV、转化率、观众分析',
          flowDifficulty: 'easy',
          tools: [TOOLS.feigua],
        },
      ],
      pros: ['选品有数据支撑', 'AI话术专业', '预热视频高效', '数据驱动复盘'],
      why: '飞瓜数据找到当前爆款选品，豆包生成专业直播话术，剪映快速制作预热短视频拉流量，直播结束后飞瓜复盘数据。所有工具国内直连，整套数据+AI话术让带货转化率显著提升。',
    },
    {
      id: 'ls2', tier: 'free', isRec: false,
      name: 'DeepSeek + 豆包 + 剪映',
      tagline: '零成本AI辅助直播，新主播入门方案',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 1,
      netSummary: 'cn',
      setupTime: '20分钟',
      timePerOutput: '随时生成话术',
      bestFor: '刚开始做直播带货的新手主播',
      scenarios: ['免费', '新手', '直播', '话术'],
      steps: [
        {
          phase: 'AI话术生成', conn: 'or',
          flowNote: '输入商品名称和卖点，生成开场白/产品介绍/促单话术',
          flowDifficulty: 'easy',
          tools: [TOOLS.deepseek, TOOLS.doubao],
        },
        {
          phase: '短视频预热', conn: 'and',
          flowNote: '剪映制作产品展示短视频，AI字幕，发布预热',
          flowDifficulty: 'medium',
          tools: [TOOLS.capcut],
        },
      ],
      pros: ['完全免费', '话术有质量', '预热视频好做', '零门槛'],
      why: '刚开始做直播带货、没有预算的新主播。DeepSeek/豆包生成专业商品话术和互动话术，剪映做预热短视频，零成本试水找到适合自己的直播风格后再投入数据工具。',
    },
    {
      id: 'ls3', tier: 'pro', isRec: false,
      name: 'HeyGen + 可灵AI + 飞瓜数据',
      tagline: 'AI虚拟主播+数据选品，7×24小时无人直播',
      priceMin: 500, priceMax: 1500,
      overallDifficulty: 4,
      netSummary: 'vpn',
      setupTime: '1-2周',
      timePerOutput: '7×24小时自动化直播',
      bestFor: '想规模化运营多账号的直播团队',
      scenarios: ['AI主播', '无人直播', '规模化', '品牌'],
      steps: [
        {
          phase: '数据选品', conn: 'and',
          flowNote: '飞瓜精准选品，分析最佳直播时段和受众',
          flowDifficulty: 'medium',
          tools: [TOOLS.feigua],
        },
        {
          phase: 'AI虚拟主播生成', conn: 'and',
          flowNote: 'HeyGen克隆真人主播，生成AI数字人口播视频循环播放',
          flowDifficulty: 'hard',
          tools: [TOOLS.heygen],
        },
        {
          phase: '直播背景视频素材', conn: 'and',
          flowNote: '可灵AI生成产品展示动态背景视频',
          flowDifficulty: 'medium',
          tools: [TOOLS.kling],
        },
      ],
      pros: ['7x24无人直播', '规模化复制', '无需真人出镜', '数据精准'],
      why: '有资金规模化运营的直播团队。HeyGen克隆真人主播实现AI虚拟主播（需梯子），可灵AI生成直播背景（国内直连），飞瓜精准选品（国内直连）。搭建复杂但运行后自动化程度高。',
    },
  ],

  // ══════════════════════════════════════════════════════
  // AI Agent自动化（agent）
  // ══════════════════════════════════════════════════════
  agent: [
    {
      id: 'ag1', tier: 'mid', isRec: true,
      name: '扣子 + Zapier + Claude',
      tagline: '无代码搭建AI自动化工作流，效率革命',
      priceMin: 20, priceMax: 100,
      overallDifficulty: 3,
      netSummary: 'vpn',
      setupTime: '3-5小时（配置工作流）',
      timePerOutput: '自动化后节省80%重复工作',
      bestFor: '想用AI自动化日常工作的非技术用户',
      scenarios: ['自动化', '工作流', '无代码', 'Bot'],
      steps: [
        {
          phase: '搭建AI Bot', conn: 'and',
          flowNote: '在扣子拖拽配置Bot，连接知识库，发布到飞书/微信等平台',
          flowDifficulty: 'medium',
          tools: [TOOLS.coze],
        },
        {
          phase: '应用集成自动化', conn: 'and',
          flowNote: 'Zapier设置触发器，连接Gmail/Notion/Slack等7000+应用',
          flowDifficulty: 'medium',
          tools: [TOOLS.zapier],
        },
        {
          phase: 'AI决策引擎', conn: 'and',
          flowNote: 'Claude API处理复杂的AI判断和内容生成任务',
          flowDifficulty: 'medium',
          tools: [TOOLS.claude35],
        },
      ],
      pros: ['无代码搭建', '7000+应用集成', 'AI智能决策', '效率大幅提升'],
      why: '无代码搭建AI工作流的最快方案。扣子搭建AI Bot（国内免费），Zapier连接7000+应用实现自动化触发（需梯子），Claude API提供AI决策能力（需梯子），三者组合可以自动化80%的重复性工作。',
    },
    {
      id: 'ag2', tier: 'free', isRec: false,
      name: '扣子 + 豆包',
      tagline: '完全免费搭建AI机器人，国内直连',
      priceMin: 0, priceMax: 0,
      overallDifficulty: 2,
      netSummary: 'cn',
      setupTime: '1小时',
      timePerOutput: '搭建后自动运行',
      bestFor: '想体验AI Agent但不想付费的用户',
      scenarios: ['免费', '国内', 'Bot', '聊天机器人'],
      steps: [
        {
          phase: '搭建Bot', conn: 'and',
          flowNote: '在扣子选择模板，配置知识库，测试对话效果',
          flowDifficulty: 'medium',
          tools: [TOOLS.coze],
        },
        {
          phase: '发布渠道', conn: 'or',
          flowNote: '一键发布到豆包或飞书，用户直接对话使用',
          flowDifficulty: 'easy',
          tools: [TOOLS.doubao,
            t('飞书', '📱', '免费', 'https://www.feishu.cn', 'cn', 1, '企业内部使用更合适'),
          ],
        },
      ],
      pros: ['完全免费', '国内直连', '发布渠道多', '无代码'],
      why: '想体验AI Agent但不想付费的用户。扣子完全免费搭建AI Bot，发布到豆包、飞书等字节系平台，零成本体验AI自动化，找到有价值的使用场景后再升级付费工具。',
    },
    {
      id: 'ag3', tier: 'pro', isRec: false,
      name: 'Dify + Claude + Supabase + Vercel',
      tagline: '私有化部署AI Agent平台，企业级方案',
      priceMin: 100, priceMax: 500,
      overallDifficulty: 5,
      netSummary: 'vpn',
      setupTime: '1-2周',
      timePerOutput: '构建完成后可服务大量用户',
      bestFor: '需要私有化AI Agent平台的技术团队',
      scenarios: ['企业', '私有化', '定制', 'Agent平台'],
      steps: [
        {
          phase: 'AI工作流平台', conn: 'and',
          flowNote: '服务器部署Dify，搭建AI工作流和知识库',
          flowDifficulty: 'hard',
          tools: [TOOLS.dify],
        },
        {
          phase: 'AI引擎', conn: 'or',
          flowNote: '配置API Key，Claude质量最高，DeepSeek成本最低',
          flowDifficulty: 'medium',
          tools: [TOOLS.claude35,
            t('DeepSeek API', '🐋', 'API极便宜', 'https://platform.deepseek.com', 'cn', 3, '国内API，成本极低，性能媲美GPT-4', 'deepseek', 0, 0),
          ],
        },
        {
          phase: '数据存储', conn: 'and',
          flowNote: 'Supabase提供PostgreSQL数据库，存储用户数据',
          flowDifficulty: 'medium',
          tools: [TOOLS.supabase],
        },
        {
          phase: '前端部署', conn: 'and',
          flowNote: 'Vercel部署前端应用，连接Supabase',
          flowDifficulty: 'easy',
          tools: [TOOLS.vercel],
        },
      ],
      pros: ['数据私有安全', '完全可定制', '成本可控', '企业级稳定'],
      why: '需要私有化AI Agent平台的技术团队。Dify提供完整LLM应用开发框架，Claude/DeepSeek API提供AI能力，Supabase存储数据，Vercel部署前端。技术门槛高，需要服务器和开发能力。',
    },
  ],
}

// ── 场景关键词匹配 ────────────────────────────────────────
export function matchScene(q: string): string {
  const lower = q.toLowerCase()
  if (/视频|剪辑|口播|短片|tiktok|抖音|youtube|vlog|成片/.test(lower)) return 'video'
  if (/公众号|写文章|写稿|图文|微信推文/.test(lower)) return 'wechat'
  if (/电商|亚马逊|跨境|选品|shopify|独立站|listing/.test(lower)) return 'ecommerce'
  if (/开发|写代码|编程|上线|app|网站|程序|软件|saas/.test(lower)) return 'dev'
  if (/绘画|生图|ai图|画图|midjourney|配图|插画|设计图/.test(lower)) return 'painting'
  if (/播客|podcast|录音|音频/.test(lower)) return 'podcast'
  if (/写作|文章|内容创作|自媒体|博客|专栏/.test(lower)) return 'writing'
  if (/ppt|演示|幻灯片|汇报|路演|pitch/.test(lower)) return 'ppt'
  if (/音乐|歌曲|作曲|配乐|歌词/.test(lower)) return 'music'
  if (/知识|学习|笔记|研究|整理|知识库/.test(lower)) return 'knowledge'
  if (/直播|带货|主播|话术|卖货/.test(lower)) return 'livestream'
  if (/agent|自动化|机器人|bot|工作流/.test(lower)) return 'agent'
  return 'video'
}

export function getCombos(scene: string): ToolCombo[] {
  return COMBOS_DB[scene] || COMBOS_DB.video
}

export const SCENE_LABELS: Record<string, string> = {
  video: '短视频创作', wechat: '公众号运营', ecommerce: '跨境电商',
  dev: '独立开发', painting: 'AI绘画变现', podcast: '播客制作',
  writing: 'AI写作', ppt: 'PPT制作', music: 'AI音乐',
  knowledge: '知识管理', livestream: '直播带货', agent: 'AI自动化',
}
