// ── 完整AI工具数据库（80+工具，12大分类）────────────────────

export interface PricePlanSimple {
  name: string      // '免费版' | 'Pro版' | 'Team版'
  price: string     // '0' | '$20' | '¥99'
  period: string    // '/月' | '/年' | '一次性'
  features: string[]
  highlight?: boolean
}

export interface TutorialVideo {
  title: string
  url: string
  platform: 'bilibili' | 'youtube'
  duration?: string   // '10分钟'
  level: 'beginner' | 'advanced'
}

export interface Tool {
  slug: string
  name: string
  maker: string
  logo: string
  category: string
  tagline: string
  desc: string
  price: string
  priceDetail: string
  pricePlans?: PricePlanSimple[]   // 结构化定价
  hasFree: boolean
  hasApi: boolean
  cnAccess: boolean
  difficulty?: 1|2|3|4|5          // 上手难度（可选，默认2）
  rating: number
  ratingCount?: number             // 评分人数
  url: string
  affiliateUrl?: string
  tags: string[]
  features: string[]
  pros: string[]
  cons: string[]
  bestFor: string
  tutorials?: TutorialVideo[]      // 入门教程视频
  useCases?: string[]              // 典型使用场景
  compareWith?: string[]           // 常见竞品slug
  updatedAt?: string               // 数据更新时间
}

export const ALL_TOOLS: Tool[] = [

  // ══════════════════════════════════════════════════════
  // 1. AI对话 & 助手
  // ══════════════════════════════════════════════════════
  {
    slug: 'chatgpt', name: 'ChatGPT', maker: 'OpenAI', logo: '💬',
    category: 'AI对话', tagline: '全球最广泛使用的AI助手',
    desc: 'OpenAI 开发的对话式 AI，支持文字、图片、代码、分析等多模态任务，GPT-4o 是目前综合能力最强的模型之一。',
    price: '免费/付费', priceDetail: '免费版有限额；Plus $20/月；Team $30/人/月',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.8,
    url: 'https://chat.openai.com',
    tags: ['对话', '写作', '代码', '分析', '图像理解'],
    features: ['GPT-4o多模态', '代码解释器', 'DALL-E 3生图', 'Plugins插件生态', '语音对话'],
    pros: ['综合能力顶级', '生态最完善', '插件丰富'],
    cons: ['需要翻墙', '付费较贵', '有速率限制'],
    bestFor: '需要高质量AI辅助的专业用户',
  },
  {
    slug: 'claude', name: 'Claude', maker: 'Anthropic', logo: '🤖',
    category: 'AI对话', tagline: '最擅长长文本理解和写作的AI',
    desc: 'Anthropic 开发，以安全性和长文本处理见长。Claude 3.5 Sonnet 在写作、分析、代码方面表现优异，支持 200K token 超长上下文。',
    price: '免费/付费', priceDetail: '免费版有限额；Pro $20/月；API按量计费',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.8,
    url: 'https://claude.ai',
    tags: ['写作', '长文本', '代码', '分析', '对话'],
    features: ['200K超长上下文', '优秀的写作能力', 'Artifacts功能', '代码生成', '文件分析'],
    pros: ['写作质量最高', '长文本处理最强', '安全性好'],
    cons: ['需要翻墙', '图像生成需第三方'],
    bestFor: '写作者、研究人员、需要处理长文档的用户',
  },
  {
    slug: 'gemini', name: 'Gemini', maker: 'Google', logo: '✨',
    category: 'AI对话', tagline: 'Google出品，深度整合搜索和生产力工具',
    desc: 'Google 最新 AI 模型，Gemini 1.5 Pro 支持百万级 token 上下文，与 Google 生产力套件深度集成，联网搜索能力强。',
    price: '免费/付费', priceDetail: '免费版；Advanced $19.99/月（含Workspace集成）',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.5,
    url: 'https://gemini.google.com',
    tags: ['对话', '搜索', '分析', 'Google集成'],
    features: ['百万token上下文', '实时联网搜索', 'Google Workspace集成', '多模态理解', '代码生成'],
    pros: ['联网能力强', 'Google生态集成', '上下文超长'],
    cons: ['需要翻墙', '中文优化不足'],
    bestFor: 'Google生态用户、需要实时信息的场景',
  },
  {
    slug: 'deepseek', name: 'DeepSeek', maker: 'DeepSeek', logo: '🐋',
    category: 'AI对话', tagline: '国产顶级AI，性能媲美GPT-4，完全免费',
    desc: '深度求索开发，DeepSeek-V3 和 R1 在推理、数学、代码领域达到国际顶级水平，国内免费使用，API价格极低。',
    price: '免费', priceDetail: '完全免费；API：输入¥1/百万token（极便宜）',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.7,
    url: 'https://chat.deepseek.com',
    tags: ['对话', '推理', '代码', '数学', '免费'],
    features: ['强推理能力', '数学/代码顶级', 'API极便宜', '国内直连', '长思考模式'],
    pros: ['完全免费', '推理能力强', '国内可用', 'API极便宜'],
    cons: ['图像生成不支持', '有时响应慢'],
    bestFor: '国内用户的首选免费AI，开发者首选API',
  },
  {
    slug: 'doubao', name: '豆包', maker: '字节跳动', logo: '🫘',
    category: 'AI对话', tagline: '字节出品，中文体验最好的AI助手',
    desc: '字节跳动旗下 AI 产品，支持对话、写作、绘图、语音，中文理解优秀，与抖音生态打通，适合内容创作者。',
    price: '免费', priceDetail: '基础功能完全免费；会员¥19.9/月解锁更多功能',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.4,
    url: 'https://www.doubao.com',
    tags: ['对话', '写作', '绘图', '语音', '免费'],
    features: ['中文写作优化', 'AI生图', '语音对话', '多角色扮演', '内容创作'],
    pros: ['完全免费', '中文体验好', '国内直连', '功能全面'],
    cons: ['API暂不开放', '专业能力弱于GPT-4'],
    bestFor: '中文内容创作者、普通用户日常使用',
  },
  {
    slug: 'kimi', name: 'Kimi', maker: '月之暗面', logo: '🌙',
    category: 'AI对话', tagline: '超长文本处理专家，支持200万字',
    desc: '月之暗面开发，以超长文本处理著称，支持上传 PDF、Word 等文件，一次处理 200 万字，适合研究和文档分析。',
    price: '免费/付费', priceDetail: '基础免费；Pro ¥99/月解锁更多额度',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.4,
    url: 'https://kimi.moonshot.cn',
    tags: ['长文本', '文档分析', 'PDF处理', '搜索'],
    features: ['200万字超长上下文', '文档上传分析', '联网搜索', '多文件对比', '智能摘要'],
    pros: ['长文本最强', '文档处理好', '国内直连'],
    cons: ['写作创意性一般', '速度有时慢'],
    bestFor: '需要处理长文档、研究报告的用户',
  },
  {
    slug: 'tongyi', name: '通义千问', maker: '阿里云', logo: '🔶',
    category: 'AI对话', tagline: '阿里出品，全模态AI，企业级可靠',
    desc: '阿里云开发的 AI 大模型，支持文字、图像、音频多模态，与阿里云生态深度整合，提供企业级 API 服务。',
    price: '免费/付费', priceDetail: '基础免费；API按量计费，新用户有免费额度',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.3,
    url: 'https://tongyi.aliyun.com',
    tags: ['对话', '多模态', '企业', 'API'],
    features: ['多模态理解', '企业级API', '阿里云集成', '长文档处理', '多语言支持'],
    pros: ['企业可靠性高', '国内直连', 'API生态完善'],
    cons: ['创意写作较弱', '界面不如竞品'],
    bestFor: '企业用户、阿里云生态用户',
  },
  {
    slug: 'wenxin', name: '文心一言', maker: '百度', logo: '🔷',
    category: 'AI对话', tagline: '百度AI，国内SEO内容创作首选',
    desc: '百度开发的 AI 大模型，与百度搜索深度整合，擅长中文内容创作和 SEO 优化，百度生态用户优先选择。',
    price: '免费/付费', priceDetail: '基础免费；专业版¥49.9/月',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.1,
    url: 'https://yiyan.baidu.com',
    tags: ['对话', '写作', '搜索', 'SEO'],
    features: ['百度搜索整合', 'SEO内容优化', '中文写作', '知识图谱', '文档生成'],
    pros: ['国内直连', '百度生态', 'SEO优化好'],
    cons: ['综合能力弱于竞品', '创意性不足'],
    bestFor: '百度生态用户、SEO内容创作',
  },
  {
    slug: 'grok', name: 'Grok', maker: 'xAI', logo: '🚀',
    category: 'AI对话', tagline: '马斯克旗下AI，实时推特数据，无审查',
    desc: 'xAI 开发，与 X（Twitter）深度整合，可实时获取推特信息，风格幽默直接，Grok-2 在创意写作方面表现突出。',
    price: '付费', priceDetail: 'X Premium+ $16/月起',
    hasFree: false, hasApi: true, cnAccess: false, rating: 4.3,
    url: 'https://grok.x.ai',
    tags: ['对话', '实时信息', '创意', 'X整合'],
    features: ['实时推特数据', '无内容审查', '创意写作强', '幽默风格', 'API开放'],
    pros: ['实时信息获取', '创意性强', '无审查限制'],
    cons: ['需要X订阅', '需要翻墙'],
    bestFor: 'X用户、需要实时信息的用户',
  },
  {
    slug: 'zhipu', name: '智谱清言', maker: '智谱AI', logo: '🧠',
    category: 'AI对话', tagline: '清华系AI，学术研究和专业分析强',
    desc: '智谱 AI 开发，GLM-4 模型，学术背景深厚，擅长逻辑推理和专业分析，提供完整 API 服务，价格实惠。',
    price: '免费/付费', priceDetail: '基础免费；API按量计费，价格实惠',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.2,
    url: 'https://chatglm.cn',
    tags: ['对话', '学术', '分析', 'API'],
    features: ['逻辑推理强', '学术分析', 'API完善', '多轮对话', '代码生成'],
    pros: ['国内直连', 'API价格低', '学术能力强'],
    cons: ['创意写作一般', '知名度较低'],
    bestFor: '学术研究者、需要低价API的开发者',
  },
  {
    slug: 'mistral', name: 'Mistral AI', maker: 'Mistral', logo: '🌬️',
    category: 'AI对话', tagline: '欧洲顶级开源AI，隐私友好',
    desc: '法国 Mistral 开发的开源大模型，Mistral Large 性能媲美 GPT-4，完全开源，隐私保护好，API 价格低。',
    price: '免费/付费', priceDetail: 'API：$2/百万token（便宜）；开源版免费部署',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.4,
    url: 'https://mistral.ai',
    tags: ['开源', 'API', '隐私', '欧洲'],
    features: ['完全开源', '低价API', '隐私保护', '多语言', '可本地部署'],
    pros: ['开源可控', 'API便宜', '隐私好'],
    cons: ['中文优化不足', '知名度低'],
    bestFor: '开发者、注重隐私的企业用户',
  },

  // ══════════════════════════════════════════════════════
  // 2. AI搜索
  // ══════════════════════════════════════════════════════
  {
    slug: 'perplexity', name: 'Perplexity', maker: 'Perplexity AI', logo: '🔍',
    category: 'AI搜索', tagline: '最好用的AI搜索引擎，实时联网有来源',
    desc: '将 AI 与实时搜索结合，回答问题时显示来源链接，研究效率比传统搜索高 5 倍，Pro 版可选择不同 AI 模型。',
    price: '免费/付费', priceDetail: '免费版每日限量；Pro $20/月无限制',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.6,
    url: 'https://www.perplexity.ai',
    tags: ['搜索', '研究', '实时信息', '引用来源'],
    features: ['实时联网搜索', '来源引用', '多模型选择', '文件上传分析', '对话式搜索'],
    pros: ['搜索质量最高', '来源可信', '研究效率高'],
    cons: ['需要翻墙', '中文覆盖弱'],
    bestFor: '研究人员、内容创作者、需要实时信息的用户',
  },
  {
    slug: 'metaso', name: '秘塔AI搜索', maker: '秘塔科技', logo: '🔎',
    category: 'AI搜索', tagline: '国内最好的AI搜索，无广告有来源',
    desc: '国内最好的 AI 搜索工具，无广告、有来源引用，支持学术搜索模式，是百度搜索的优质替代品。',
    price: '免费', priceDetail: '完全免费',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.5,
    url: 'https://metaso.cn',
    tags: ['搜索', '国内', '免费', '无广告'],
    features: ['无广告搜索', '来源引用', '学术模式', '国内直连', '深度搜索'],
    pros: ['完全免费', '国内直连', '无广告', '来源可信'],
    cons: ['英文信息弱于Perplexity'],
    bestFor: '国内用户的Google/百度替代品',
  },
  {
    slug: 'phind', name: 'Phind', maker: 'Phind', logo: '👨‍💻',
    category: 'AI搜索', tagline: '专为开发者设计的AI搜索引擎',
    desc: '专注于技术和代码的 AI 搜索，理解编程问题，搜索结果优先展示技术文档和 GitHub，开发者效率神器。',
    price: '免费/付费', priceDetail: '免费版有限额；Pro $20/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://www.phind.com',
    tags: ['搜索', '开发', '代码', '技术'],
    features: ['代码搜索优化', 'GitHub整合', '技术文档优先', '多语言代码', '开发者工作流'],
    pros: ['开发者体验最好', '代码理解准确'],
    cons: ['非技术内容弱', '需要翻墙'],
    bestFor: '程序员、技术开发者',
  },
  {
    slug: 'you', name: 'You.com', maker: 'You.com', logo: '🌐',
    category: 'AI搜索', tagline: '可定制AI搜索，隐私保护强',
    desc: '可定制化 AI 搜索引擎，支持多种 AI 模型切换，隐私保护好，有 AI 写作、代码等专项功能。',
    price: '免费/付费', priceDetail: '免费版；Pro $15/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.1,
    url: 'https://you.com',
    tags: ['搜索', '隐私', '定制'],
    features: ['多模型支持', '隐私保护', 'AI写作模式', 'AI代码模式', '搜索定制'],
    pros: ['隐私好', '可定制', '多模型'],
    cons: ['搜索质量弱于Perplexity'],
    bestFor: '注重隐私的用户',
  },

  // ══════════════════════════════════════════════════════
  // 3. AI写作
  // ══════════════════════════════════════════════════════
  {
    slug: 'jasper', name: 'Jasper', maker: 'Jasper AI', logo: '📝',
    category: 'AI写作', tagline: '营销文案专业AI写作平台',
    desc: '专为营销团队设计的 AI 写作平台，支持品牌声音设置，60+ 写作模板，与 SEO 工具集成，适合营销内容批量生产。',
    price: '付费', priceDetail: 'Creator $39/月；Pro $59/月；Business定制',
    hasFree: false, hasApi: false, cnAccess: false, rating: 4.2,
    url: 'https://www.jasper.ai',
    tags: ['营销', '文案', '品牌', 'SEO'],
    features: ['品牌声音定制', '60+写作模板', 'SEO集成', '多语言', '团队协作'],
    pros: ['营销内容专业', '品牌一致性好', '模板丰富'],
    cons: ['价格较贵', '需要翻墙', '通用写作弱'],
    bestFor: '营销团队、品牌内容创作者',
  },
  {
    slug: 'copyai', name: 'Copy.ai', maker: 'Copy.ai', logo: '✍️',
    category: 'AI写作', tagline: '营销文案批量生产，工作流自动化',
    desc: '专注营销文案的 AI 写作工具，90+ 种文案模板，支持工作流自动化，可批量生产广告、邮件、社媒内容。',
    price: '免费/付费', priceDetail: '免费2000字/月；Pro $49/月；Team $249/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.1,
    url: 'https://www.copy.ai',
    tags: ['营销', '文案', '批量', '工作流'],
    features: ['90+文案模板', '工作流自动化', '批量生产', '多平台适配', '多语言'],
    pros: ['批量效率高', '模板丰富', '工作流强'],
    cons: ['需要翻墙', '价格偏高'],
    bestFor: '电商卖家、营销团队、批量内容生产',
  },
  {
    slug: 'grammarly', name: 'Grammarly', maker: 'Grammarly', logo: '📖',
    category: 'AI写作', tagline: '英文写作校对和润色神器',
    desc: '全球最广泛使用的英文写作助手，AI 驱动的语法检查、风格优化、语气调整，浏览器插件随时使用。',
    price: '免费/付费', priceDetail: '免费基础版；Premium $12/月；Business $15/人/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://www.grammarly.com',
    tags: ['英文', '校对', '润色', '浏览器插件'],
    features: ['实时语法检查', '风格建议', '语气优化', '抄袭检测', '浏览器插件'],
    pros: ['英文校对最强', '随处可用', '免费版够用'],
    cons: ['仅限英文', '中文不支持'],
    bestFor: '英文写作者、外贸从业者',
  },
  {
    slug: 'notion-ai', name: 'Notion AI', maker: 'Notion', logo: '📋',
    category: 'AI写作', tagline: '嵌入Notion的AI写作助手',
    desc: '直接内嵌在 Notion 中的 AI 功能，可在笔记中直接写作、总结、翻译、改写，不需要切换工具。',
    price: '付费', priceDetail: 'Notion AI附加项 $10/人/月（需已有Notion账号）',
    hasFree: false, hasApi: false, cnAccess: false, rating: 4.3,
    url: 'https://www.notion.so/product/ai',
    tags: ['写作', '笔记', '总结', 'Notion'],
    features: ['嵌入式写作', '智能总结', '自动翻译', '内容改写', '数据库联动'],
    pros: ['与Notion无缝集成', '工作流顺畅', '多功能'],
    cons: ['需要Notion订阅', '价格叠加'],
    bestFor: 'Notion重度用户、内容管理者',
  },
  {
    slug: 'xiezuocat', name: '写作猫', maker: '秘塔科技', logo: '🐱',
    category: 'AI写作', tagline: '中文写作校对和AI写作国内首选',
    desc: '秘塔科技旗下中文写作工具，AI 辅助写作、错别字检测、语法校对、降重改写，是中文写作者的得力助手。',
    price: '免费/付费', priceDetail: '基础免费；会员¥98/年',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.3,
    url: 'https://xiezuocat.com',
    tags: ['中文', '校对', '改写', '降重'],
    features: ['中文语法校对', 'AI写作辅助', '降重改写', '错别字检测', '文风分析'],
    pros: ['中文最专业', '国内直连', '价格实惠'],
    cons: ['英文支持弱'],
    bestFor: '中文内容创作者、学生、媒体从业者',
  },

  // ══════════════════════════════════════════════════════
  // 4. AI编程开发
  // ══════════════════════════════════════════════════════
  {
    slug: 'cursor', name: 'Cursor', maker: 'Anysphere', logo: '⌨️',
    category: 'AI编程', tagline: '目前最强AI编程IDE，独立开发者首选',
    desc: '基于 VS Code 的 AI 编程 IDE，支持整个代码库理解，自然语言写代码，AI 解释和修复 Bug，是目前最好的 AI 编程工具。',
    price: '免费/付费', priceDetail: '免费2周试用；Pro $20/月；Business $40/月',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.8,
    url: 'https://cursor.sh',
    tags: ['编程', 'IDE', '代码生成', '全栈'],
    features: ['整库代码理解', '自然语言编程', 'Tab补全', 'AI调试', '多语言支持'],
    pros: ['编程体验最好', '代码库理解深', '全语言支持'],
    cons: ['价格偏高', '新用户有学习成本'],
    bestFor: '独立开发者、全栈工程师',
  },
  {
    slug: 'github-copilot', name: 'GitHub Copilot', maker: 'GitHub/Microsoft', logo: '🐙',
    category: 'AI编程', tagline: '微软GitHub出品，企业级AI编程助手',
    desc: '微软和 GitHub 联合开发，深度整合在 GitHub 生态中，支持 VS Code、JetBrains 等主流 IDE，企业采购首选。',
    price: '付费', priceDetail: 'Individual $10/月；Business $19/人/月',
    hasFree: false, hasApi: false, cnAccess: true, rating: 4.5,
    url: 'https://github.com/features/copilot',
    tags: ['编程', 'GitHub', '企业', 'IDE插件'],
    features: ['主流IDE集成', 'GitHub深度整合', '代码审查', '测试生成', '多语言'],
    pros: ['企业信任度高', 'GitHub集成好', '稳定可靠'],
    cons: ['需要付费', '不如Cursor灵活'],
    bestFor: '企业开发团队、GitHub重度用户',
  },
  {
    slug: 'codeium', name: 'Codeium', maker: 'Exafunction', logo: '💚',
    category: 'AI编程', tagline: '免费的AI代码补全，媲美Copilot',
    desc: '完全免费的 AI 代码补全工具，支持 70+ 种编程语言，可集成到 VS Code、JetBrains 等 IDE，个人用户的最佳 Copilot 替代。',
    price: '免费', priceDetail: '个人完全免费；Teams $12/人/月',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.4,
    url: 'https://codeium.com',
    tags: ['编程', '免费', '代码补全', 'IDE插件'],
    features: ['70+语言支持', '完全免费', '主流IDE集成', '智能补全', '代码解释'],
    pros: ['完全免费', '支持语言多', '质量接近Copilot'],
    cons: ['功能不如Cursor全面'],
    bestFor: '预算有限的开发者、学生',
  },
  {
    slug: 'v0', name: 'v0', maker: 'Vercel', logo: '▲',
    category: 'AI编程', tagline: '文字描述直接生成前端UI代码',
    desc: 'Vercel 出品，输入自然语言描述，直接生成 React/Next.js 前端组件代码，可一键部署，前端开发效率革命。',
    price: '免费/付费', priceDetail: '免费有限额；Pro $20/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.6,
    url: 'https://v0.dev',
    tags: ['前端', 'React', 'UI生成', 'Vercel'],
    features: ['自然语言生成UI', 'React/Tailwind代码', '一键Vercel部署', '组件迭代', '响应式设计'],
    pros: ['前端生成最快', '代码质量高', '一键部署'],
    cons: ['仅限前端', '需要翻墙'],
    bestFor: '前端开发者、全栈独立开发者',
  },
  {
    slug: 'bolt', name: 'Bolt.new', maker: 'StackBlitz', logo: '⚡',
    category: 'AI编程', tagline: '全栈AI开发，浏览器直接运行',
    desc: 'StackBlitz 出品，在浏览器中直接生成、运行、部署全栈应用，支持 React、Vue、Node.js，不需要本地环境。',
    price: '免费/付费', priceDetail: '免费版有限额；Pro $20/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://bolt.new',
    tags: ['全栈', '浏览器', '快速原型', 'AI开发'],
    features: ['浏览器全栈运行', '全栈应用生成', '即时预览', '一键部署', 'npm支持'],
    pros: ['无需环境配置', '全栈能力强', '速度快'],
    cons: ['复杂项目受限', '需要翻墙'],
    bestFor: '快速原型开发、非技术创始人验证想法',
  },
  {
    slug: 'tongyi-lingma', name: '通义灵码', maker: '阿里云', logo: '🔶',
    category: 'AI编程', tagline: '国内最好的AI编程助手，完全免费',
    desc: '阿里云出品，国内可用的免费 AI 编程助手，支持 VS Code 和 JetBrains，代码补全质量优秀，企业级安全保障。',
    price: '免费', priceDetail: '个人完全免费；企业版定制',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.3,
    url: 'https://tongyi.aliyun.com/lingma',
    tags: ['编程', '国内', '免费', 'IDE插件'],
    features: ['国内直连', '完全免费', 'VS Code集成', 'JetBrains集成', '中文注释'],
    pros: ['国内可用', '完全免费', '企业级安全'],
    cons: ['能力弱于Cursor'],
    bestFor: '国内开发者首选免费编程助手',
  },
  {
    slug: 'devin', name: 'Devin', maker: 'Cognition AI', logo: '🤖',
    category: 'AI编程', tagline: '全球首个AI软件工程师，自主完成编程任务',
    desc: 'Cognition AI 开发的首个 AI 软件工程师，可自主完成完整编程任务，包括需求分析、代码编写、测试、部署全流程。',
    price: '付费', priceDetail: '$500/月起',
    hasFree: false, hasApi: false, cnAccess: false, rating: 4.0,
    url: 'https://devin.ai',
    tags: ['AI工程师', '自主编程', '全流程'],
    features: ['自主完成任务', '全流程开发', '需求理解', '代码+测试+部署', '自我纠错'],
    pros: ['自主性最强', '全流程自动化'],
    cons: ['价格极贵', '尚在早期'],
    bestFor: '有资金的团队，用于解放工程师',
  },

  // ══════════════════════════════════════════════════════
  // 5. AI图像生成
  // ══════════════════════════════════════════════════════
  {
    slug: 'midjourney', name: 'Midjourney', maker: 'Midjourney', logo: '🎨',
    category: 'AI图像', tagline: '图像质量最高的AI绘画工具',
    desc: '目前图像质量最高、最具艺术感的 AI 绘图工具，Discord 上使用，擅长写实、艺术风格多样，是 AI 绘画的行业标准。',
    price: '付费', priceDetail: 'Basic $10/月；Standard $30/月；Pro $60/月',
    hasFree: false, hasApi: false, cnAccess: false, rating: 4.8,
    url: 'https://www.midjourney.com',
    tags: ['图像', '艺术', '写实', '商业'],
    features: ['顶级图像质量', '多风格支持', 'Vary细节调整', '图生图', '商业授权'],
    pros: ['质量最高', '风格最多', '商业可用'],
    cons: ['需Discord', '需要翻墙', '需付费'],
    bestFor: '专业设计师、商业插图创作者',
  },
  {
    slug: 'stable-diffusion', name: 'Stable Diffusion', maker: 'Stability AI', logo: '🌊',
    category: 'AI图像', tagline: '开源AI绘画，可本地部署无限生图',
    desc: '完全开源的 AI 图像生成模型，可本地部署，支持 LoRA 微调，社区模型丰富，无内容限制，是技术用户的首选。',
    price: '免费', priceDetail: '开源免费，需要本地GPU或云端部署',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.5,
    url: 'https://stability.ai',
    tags: ['开源', '本地部署', 'LoRA', '无限制'],
    features: ['完全开源', '本地部署', 'LoRA微调', '社区模型库', 'ComfyUI工作流'],
    pros: ['完全免费', '可定制', '无内容限制', '社区活跃'],
    cons: ['需要技术门槛', '本地需要GPU'],
    bestFor: '技术用户、AI绘画深度玩家',
  },
  {
    slug: 'dalle3', name: 'DALL-E 3', maker: 'OpenAI', logo: '🖼️',
    category: 'AI图像', tagline: 'ChatGPT内置，提示词理解最准确',
    desc: 'OpenAI 开发，与 ChatGPT 深度集成，提示词理解最准确，特别擅长文字嵌入图片，可以在聊天中直接生图。',
    price: '付费', priceDetail: '含在ChatGPT Plus $20/月；API按图计费',
    hasFree: false, hasApi: true, cnAccess: false, rating: 4.6,
    url: 'https://openai.com/dall-e-3',
    tags: ['图像', 'ChatGPT', '文字嵌入', '提示词准确'],
    features: ['提示词理解最准', '文字嵌入图片', 'ChatGPT集成', 'API调用', '多种尺寸'],
    pros: ['提示词理解强', '文字处理好', '集成方便'],
    cons: ['需要付费', '风格不如Midjourney多'],
    bestFor: 'ChatGPT Plus用户、需要精准内容图片的场景',
  },
  {
    slug: 'flux', name: 'Flux', maker: 'Black Forest Labs', logo: '⚡',
    category: 'AI图像', tagline: '新一代开源图像生成，超越SD',
    desc: 'Black Forest Labs 开发的新一代图像生成模型，在写实性和文字理解上超越 Stable Diffusion，已成为 SD 最热门替代品。',
    price: '免费/付费', priceDetail: '开源版免费；API $0.003/张起',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.6,
    url: 'https://blackforestlabs.ai',
    tags: ['开源', '写实', '新一代', 'API'],
    features: ['超强写实性', '文字理解好', '开源可部署', '快速生成', '高分辨率'],
    pros: ['写实最强', '开源免费', '进化快'],
    cons: ['需要技术部署'],
    bestFor: '技术用户、商业写实图像需求',
  },
  {
    slug: 'jimeng', name: '即梦AI', maker: '字节跳动', logo: '🌙',
    category: 'AI图像', tagline: '字节出品，国内免费AI生图首选',
    desc: '字节跳动出品，国内直接访问，免费生图质量优秀，支持图生图、风格迁移，与剪映深度集成，是国内 AI 创作者首选。',
    price: '免费/付费', priceDetail: '基础免费每日有限额；会员解锁更多',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.4,
    url: 'https://jimeng.jianying.com',
    tags: ['图像', '国内', '免费', '视频'],
    features: ['国内免费生图', '图生图', '风格迁移', 'AI视频生成', '剪映集成'],
    pros: ['国内直连', '免费', '质量好', '视频也支持'],
    cons: ['每日限额', '商业授权不明确'],
    bestFor: '国内AI创作者、自媒体人',
  },
  {
    slug: 'wenxin-yige', name: '文心一格', maker: '百度', logo: '🎭',
    category: 'AI图像', tagline: '百度AI绘画，中文提示词最友好',
    desc: '百度文心大模型驱动的 AI 绘画平台，中文提示词支持最好，国内直连免费，与百度生态整合，适合中文用户。',
    price: '免费/付费', priceDetail: '基础免费有电量限制；会员¥9.9/月',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.0,
    url: 'https://yige.baidu.com',
    tags: ['图像', '中文', '国内', '免费'],
    features: ['中文提示词优化', '国内直连', '多风格', '创意工坊', '商品图生成'],
    pros: ['中文最友好', '国内直连', '基础免费'],
    cons: ['质量弱于Midjourney', '每日限额'],
    bestFor: '中文用户、初学者',
  },
  {
    slug: 'ideogram', name: 'Ideogram', maker: 'Ideogram AI', logo: '💡',
    category: 'AI图像', tagline: '文字嵌入图片最准确的AI生图工具',
    desc: '专注于文字嵌入图片的 AI 生图工具，在图片中准确渲染文字的能力全球领先，适合 Logo、海报、文字图设计。',
    price: '免费/付费', priceDetail: '免费每日限额；Basic $7/月；Plus $16/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://ideogram.ai',
    tags: ['图像', '文字', 'Logo', '海报'],
    features: ['文字嵌入最准', 'Logo生成', '海报设计', '多语言文字', '风格多样'],
    pros: ['文字图片最强', '适合商业设计'],
    cons: ['需要翻墙', '综合质量不如MJ'],
    bestFor: 'Logo设计师、海报创作者、社媒内容创作',
  },
  {
    slug: 'leonardo', name: 'Leonardo AI', maker: 'Leonardo.Ai', logo: '🦁',
    category: 'AI图像', tagline: '游戏美术和写实图像专业平台',
    desc: '专注于游戏美术和高质量图像的 AI 平台，支持自定义模型训练，素材生产工具完善，游戏和创意行业广泛使用。',
    price: '免费/付费', priceDetail: '免费150积分/天；Apprentice $10/月；Artisan $24/月',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.4,
    url: 'https://leonardo.ai',
    tags: ['游戏', '写实', '商业', 'API'],
    features: ['游戏美术优化', '自定义模型训练', '素材批量生产', '图生图', 'API支持'],
    pros: ['游戏美术最专业', '自定义强', 'API支持'],
    cons: ['需要翻墙', '学习成本高'],
    bestFor: '游戏开发者、商业插图师',
  },

  // ══════════════════════════════════════════════════════
  // 6. AI视频生成
  // ══════════════════════════════════════════════════════
  {
    slug: 'runway', name: 'Runway Gen-3', maker: 'Runway', logo: '🎥',
    category: 'AI视频', tagline: '专业级AI视频生成，好莱坞导演在用',
    desc: 'Runway Gen-3 Alpha 是目前最专业的 AI 视频生成工具，画面质量和运动流畅度领先业界，已有好莱坞级别应用案例。',
    price: '付费', priceDetail: 'Standard $15/月；Pro $35/月；Unlimited $95/月',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.6,
    url: 'https://runwayml.com',
    tags: ['视频', '专业', '文生视频', '图生视频'],
    features: ['Gen-3最高质量', '文生视频', '图生视频', '视频编辑', '运动笔刷'],
    pros: ['视频质量最高', '专业功能多', '好莱坞认可'],
    cons: ['价格贵', '需要翻墙', '速度慢'],
    bestFor: '专业视频创作者、广告公司',
  },
  {
    slug: 'sora', name: 'Sora', maker: 'OpenAI', logo: '🌀',
    category: 'AI视频', tagline: 'OpenAI划时代视频生成，物理世界理解最强',
    desc: 'OpenAI 发布的视频生成模型，对物理世界的理解和长视频生成能力领先，已向 ChatGPT Plus 用户开放。',
    price: '付费', priceDetail: '含在ChatGPT Plus $20/月（有限额）',
    hasFree: false, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://sora.com',
    tags: ['视频', 'OpenAI', '物理模拟', '长视频'],
    features: ['物理世界理解', '最长60秒视频', '文生视频', '图生视频', '视频编辑'],
    pros: ['物理模拟最真实', 'OpenAI背书', '视频长度长'],
    cons: ['需要Plus订阅', '需要翻墙', '速度慢'],
    bestFor: '需要高质量AI视频的创作者',
  },
  {
    slug: 'kling', name: '可灵AI', maker: '快手', logo: '🦋',
    category: 'AI视频', tagline: '国内最强AI视频，写实运动流畅',
    desc: '快手出品的 AI 视频生成工具，写实视频质量和运动流畅度在国内领先，支持最长3分钟视频，国内直连免费试用。',
    price: '免费/付费', priceDetail: '基础功能免费试用；会员¥66-399/月',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.5,
    url: 'https://klingai.kuaishou.com',
    tags: ['视频', '写实', '国内', '长视频'],
    features: ['写实视频强', '最长3分钟', '图生视频', '文生视频', '人物一致性'],
    pros: ['国内直连', '质量好', '视频较长'],
    cons: ['高质量需付费', '速度慢'],
    bestFor: '国内AI视频创作者首选',
  },
  {
    slug: 'vidu', name: 'Vidu', maker: '生数科技', logo: '🎬',
    category: 'AI视频', tagline: '国产AI视频，人物一致性突出',
    desc: '生数科技与清华大学合作开发，在人物一致性和表情细节方面表现突出，支持多镜头、角色保持一致。',
    price: '免费/付费', priceDetail: '基础免费；会员¥99/月',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.2,
    url: 'https://www.vidu.cn',
    tags: ['视频', '人物', '国内', '一致性'],
    features: ['人物一致性强', '多镜头连贯', '表情细节', '文生视频', '图生视频'],
    pros: ['人物一致性最好', '国内直连'],
    cons: ['质量波动大', '功能尚不完善'],
    bestFor: '需要人物一致性的视频创作者',
  },
  {
    slug: 'heygen', name: 'HeyGen', maker: 'HeyGen', logo: '🎭',
    category: 'AI视频', tagline: 'AI数字人口播，声音克隆视频制作',
    desc: '专注于 AI 数字人视频生成，可克隆真人形象和声音，一键生成多语言口播视频，已有大量企业和 KOL 采用。',
    price: '付费', priceDetail: 'Creator $29/月；Business $89/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.6,
    url: 'https://www.heygen.com',
    tags: ['数字人', '口播', '声音克隆', '多语言'],
    features: ['真人形象克隆', '声音克隆', '多语言翻译', '口型同步', '批量生成'],
    pros: ['数字人最专业', '声音克隆准确', '多语言支持'],
    cons: ['需要付费', '需要翻墙'],
    bestFor: '企业宣传、多语言内容创作者、KOL',
  },
  {
    slug: 'pika', name: 'Pika', maker: 'Pika Labs', logo: '💫',
    category: 'AI视频', tagline: '快速创意视频，修改已有视频神器',
    desc: 'Pika 1.5 在快速生成创意视频和修改已有视频方面表现优秀，Pikaffects 特效功能独特，适合社媒创意内容。',
    price: '免费/付费', priceDetail: '免费500积分/月；Standard $8/月；Pro $28/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.2,
    url: 'https://pika.art',
    tags: ['视频', '创意', '特效', '快速'],
    features: ['快速生成', '视频修改', 'Pikaffects特效', '图生视频', '风格迁移'],
    pros: ['速度快', '特效独特', '价格便宜'],
    cons: ['质量不如Runway', '需要翻墙'],
    bestFor: '社媒创意内容、快速制作短视频特效',
  },

  // ══════════════════════════════════════════════════════
  // 7. AI音频 & 语音
  // ══════════════════════════════════════════════════════
  {
    slug: 'elevenlabs', name: 'ElevenLabs', maker: 'ElevenLabs', logo: '🎙️',
    category: 'AI音频', tagline: '最真实的AI语音克隆和TTS',
    desc: '目前语音克隆效果最好的 AI 工具，可用3秒音频克隆声音，支持30+语言，API完善，大量播客和视频创作者在用。',
    price: '免费/付费', priceDetail: '免费1万字符/月；Starter $5/月；Creator $22/月',
    hasFree: true, hasApi: true, cnAccess: false, rating: 4.7,
    url: 'https://elevenlabs.io',
    tags: ['语音', '克隆', 'TTS', '多语言'],
    features: ['3秒声音克隆', '30+语言支持', '情感语音', 'API完善', '实时语音'],
    pros: ['克隆效果最真实', '多语言支持', 'API强'],
    cons: ['需要翻墙', '免费额度有限'],
    bestFor: '视频配音、播客制作、多语言内容创作',
  },
  {
    slug: 'suno', name: 'Suno', maker: 'Suno AI', logo: '🎵',
    category: 'AI音频', tagline: '文字生成完整歌曲，AI作曲革命',
    desc: '输入歌词或风格描述，直接生成完整歌曲（含人声+音乐），Suno v4 生成的歌曲已接近专业水准，掀起 AI 音乐革命。',
    price: '免费/付费', priceDetail: '免费50积分/天；Pro $8/月；Premier $24/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://suno.com',
    tags: ['音乐', '歌曲', '作曲', '创作'],
    features: ['完整歌曲生成', '人声+音乐', '风格多样', '歌词自定义', '续写音乐'],
    pros: ['歌曲质量高', '操作简单', '风格丰富'],
    cons: ['需要翻墙', '版权问题复杂'],
    bestFor: '内容创作者配乐、音乐爱好者',
  },
  {
    slug: 'udio', name: 'Udio', maker: 'Udio', logo: '🎶',
    category: 'AI音频', tagline: 'AI音乐生成，Suno最强竞品',
    desc: 'Suno 的主要竞品，在音乐细节和专业性上有独特优势，支持更精细的音乐风格控制，专业音乐人也在使用。',
    price: '免费/付费', priceDetail: '免费100积分/月；Standard $10/月；Pro $30/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://www.udio.com',
    tags: ['音乐', '专业', '风格控制'],
    features: ['精细风格控制', '专业音质', '多轨编辑', '自定义歌词', '音乐延伸'],
    pros: ['音乐细节好', '专业控制强'],
    cons: ['需要翻墙', '学习成本高'],
    bestFor: '音乐制作人、专业内容创作者',
  },
  {
    slug: 'volcengine-tts', name: '火山引擎TTS', maker: '字节跳动', logo: '🔊',
    category: 'AI音频', tagline: '字节云端TTS，国内最好用的语音合成API',
    desc: '字节跳动火山引擎提供的 TTS API，音色多样，中文效果极好，价格低廉，国内开发者首选语音合成方案。',
    price: '付费', priceDetail: '按字符计费，约¥0.05/千字符，新用户有免费额度',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.3,
    url: 'https://www.volcengine.com/product/tts',
    tags: ['TTS', 'API', '国内', '中文'],
    features: ['中文效果好', '音色多样', 'API调用', '实时流式', '情感控制'],
    pros: ['国内直连', 'API稳定', '价格低', '中文最好'],
    cons: ['需要注册企业账号'],
    bestFor: '国内开发者、需要TTS API的应用',
  },
  {
    slug: 'iflytek', name: '讯飞听见', maker: '科大讯飞', logo: '🎤',
    category: 'AI音频', tagline: '中文语音转文字最准确，会议记录神器',
    desc: '科大讯飞出品，中文语音识别准确率行业第一，支持实时转写、会议记录、多人分离，是会议和播客记录的首选工具。',
    price: '免费/付费', priceDetail: '基础免费有限额；会员¥9.9/月；API按量计费',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.5,
    url: 'https://www.iflyrec.com',
    tags: ['语音识别', '转写', '会议', '中文'],
    features: ['中文识别最准', '实时转写', '多人声音分离', '方言支持', '会议纪要'],
    pros: ['中文准确率最高', '国内直连', '方言支持'],
    cons: ['英文支持弱'],
    bestFor: '会议记录、播客转写、内容创作者',
  },
  {
    slug: 'descript', name: 'Descript', maker: 'Descript', logo: '🎧',
    category: 'AI音频', tagline: '音频视频编辑神器，像编辑文档一样剪音频',
    desc: 'Descript 革命性地让用户像编辑文字一样编辑音频/视频，自动转写后，删文字即删对应音频，播客和视频制作效率翻倍。',
    price: '免费/付费', priceDetail: '免费版有限制；Creator $24/月；Business $40/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://www.descript.com',
    tags: ['音频', '视频', '转写', '播客'],
    features: ['文字即音频编辑', '自动降噪', 'AI转写', '去除口头禅', '声音克隆'],
    pros: ['编辑方式革命性', '降噪效果好', '播客首选'],
    cons: ['需要翻墙', '价格不低'],
    bestFor: '播客制作者、视频内容创作者',
  },

  // ══════════════════════════════════════════════════════
  // 8. AI演示文稿 & 办公
  // ══════════════════════════════════════════════════════
  {
    slug: 'gamma', name: 'Gamma', maker: 'Gamma App', logo: '📊',
    category: 'AI办公', tagline: 'AI一键生成PPT，设计感极强',
    desc: '输入主题或内容，AI 自动生成设计精美的 PPT/文档/网页，设计质量远超传统 PowerPoint，已被百万用户使用。',
    price: '免费/付费', priceDetail: '免费400积分；Plus $8/月；Pro $15/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.6,
    url: 'https://gamma.app',
    tags: ['PPT', '演示', '设计', '一键生成'],
    features: ['AI自动生成PPT', '设计精美', '多主题模板', '在线协作', '多格式导出'],
    pros: ['设计质量高', '操作简单', '速度快'],
    cons: ['需要翻墙', '定制化有限'],
    bestFor: '需要快速制作精美PPT的商务人士',
  },
  {
    slug: 'tome', name: 'Tome', maker: 'Tome', logo: '📖',
    category: 'AI办公', tagline: 'AI叙事型演示文稿，讲故事神器',
    desc: '专注于叙事型演示的 AI 工具，生成的 PPT 更像一个故事，适合投资人路演、产品演示等需要讲故事的场景。',
    price: '免费/付费', priceDetail: '免费版；Pro $20/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.2,
    url: 'https://tome.app',
    tags: ['PPT', '叙事', '路演', '故事'],
    features: ['叙事型设计', 'AI内容生成', '动效丰富', '嵌入媒体', '分享便捷'],
    pros: ['叙事感强', '动效好看'],
    cons: ['需要翻墙', '功能较单一'],
    bestFor: '路演演讲者、产品经理',
  },
  {
    slug: 'aippt', name: 'AiPPT', maker: 'AiPPT', logo: '📑',
    category: 'AI办公', tagline: '国内AI PPT制作，无需翻墙',
    desc: '国内优质 AI PPT 制作工具，上传文档或输入主题即可一键生成，提供丰富模板，无需翻墙，价格实惠。',
    price: '免费/付费', priceDetail: '基础免费；会员¥99/年',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.1,
    url: 'https://www.aippt.cn',
    tags: ['PPT', '国内', '免费', '模板'],
    features: ['一键生成PPT', '文档转PPT', '丰富模板', '国内直连', 'AI美化'],
    pros: ['国内直连', '价格实惠', '操作简单'],
    cons: ['质量弱于Gamma', '设计感较普通'],
    bestFor: '国内商务用户、学生',
  },
  {
    slug: 'monica', name: 'Monica', maker: 'Monica AI', logo: '🧩',
    category: 'AI办公', tagline: '浏览器AI助手，全网一键AI化',
    desc: '浏览器插件形式的 AI 助手，可在任何网页上直接使用 AI，支持网页总结、翻译、写作、搜索，是效率工具的集大成者。',
    price: '免费/付费', priceDetail: '免费版有限额；Pro $8.3/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://monica.im',
    tags: ['浏览器插件', '效率', '全能', '翻译'],
    features: ['网页任意位置使用', '一键总结网页', '实时翻译', 'AI写作', '多模型切换'],
    pros: ['随处可用', '功能全面', '多模型'],
    cons: ['需要翻墙', '依赖网络'],
    bestFor: '效率工具爱好者、内容研究者',
  },
  {
    slug: 'wps-ai', name: 'WPS AI', maker: '金山软件', logo: '📄',
    category: 'AI办公', tagline: '国内Office AI，深度集成WPS',
    desc: '金山 WPS 内置的 AI 功能，可在 Word/Excel/PPT 中直接使用 AI 写作、分析、生成，无需翻墙，国内办公首选。',
    price: '免费/付费', priceDetail: 'WPS会员含AI功能，¥35/月',
    hasFree: false, hasApi: false, cnAccess: true, rating: 4.1,
    url: 'https://ai.wps.cn',
    tags: ['Office', '国内', 'Word', 'Excel'],
    features: ['Word/Excel/PPT集成', 'AI写作', '数据分析', '国内直连', '企业协作'],
    pros: ['国内直连', 'Office深度集成', '企业可信'],
    cons: ['需要会员订阅', '功能不如专业AI工具'],
    bestFor: '国内企业用户、Office重度用户',
  },

  // ══════════════════════════════════════════════════════
  // 9. AI数据分析
  // ══════════════════════════════════════════════════════
  {
    slug: 'julius', name: 'Julius AI', maker: 'Julius', logo: '📈',
    category: 'AI数据', tagline: '上传Excel/CSV，AI自动分析出图',
    desc: '数据分析 AI，上传 Excel、CSV、数据库，用自然语言提问即可生成图表、分析报告，不需要会 SQL 或 Python。',
    price: '免费/付费', priceDetail: '免费有限制；Pro $20/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://julius.ai',
    tags: ['数据分析', 'Excel', '图表', 'SQL'],
    features: ['自然语言分析数据', 'Excel/CSV上传', '自动生成图表', '统计分析', '报告生成'],
    pros: ['无需技术背景', '操作简单', '图表美观'],
    cons: ['需要翻墙', '复杂分析有限'],
    bestFor: '非技术背景的数据分析师、运营人员',
  },
  {
    slug: 'helium10', name: 'Helium 10', maker: 'Helium 10', logo: '🔬',
    category: 'AI数据', tagline: '亚马逊卖家最强选品数据工具',
    desc: '跨境电商卖家必备工具，提供亚马逊关键词研究、竞品分析、选品数据、排名追踪等完整数据服务，AI 辅助决策。',
    price: '付费', priceDetail: 'Starter $29/月；Platinum $79/月；Diamond $229/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://www.helium10.com',
    tags: ['电商', '亚马逊', '选品', '数据'],
    features: ['关键词研究', '竞品分析', '选品数据', '排名追踪', 'PPC优化'],
    pros: ['数据最全面', '亚马逊专业', '功能完善'],
    cons: ['需要翻墙', '价格不低', '学习成本'],
    bestFor: '亚马逊卖家、跨境电商从业者',
  },
  {
    slug: 'feigua', name: '飞瓜数据', maker: '飞瓜数据', logo: '🍉',
    category: 'AI数据', tagline: '抖音快手数据分析，国内自媒体必备',
    desc: '专注于抖音、快手、小红书的数据分析平台，提供账号分析、爆款追踪、达人榜单、商品选品数据，国内自媒体必备。',
    price: '付费', priceDetail: '基础版¥99/月；专业版¥399/月',
    hasFree: false, hasApi: false, cnAccess: true, rating: 4.4,
    url: 'https://www.feigua.io',
    tags: ['抖音', '数据', '国内', '自媒体'],
    features: ['抖音数据分析', '快手数据', '小红书数据', '爆款追踪', '达人榜单'],
    pros: ['国内直连', '数据全面', '平台专业'],
    cons: ['价格较高', '仅限国内平台'],
    bestFor: '抖音运营者、MCN机构、带货选品',
  },

  // ══════════════════════════════════════════════════════
  // 10. AI Agent & 自动化
  // ══════════════════════════════════════════════════════
  {
    slug: 'manus', name: 'Manus', maker: 'Monica AI', logo: '🖐️',
    category: 'AI Agent', tagline: '首个通用AI Agent，自主完成复杂任务',
    desc: '全球首个通用型 AI Agent，可自主浏览网页、操作软件、处理文件、完成复杂多步骤任务，无需人工干预。',
    price: '付费', priceDetail: '邀请制内测，定价待定',
    hasFree: false, hasApi: false, cnAccess: true, rating: 4.2,
    url: 'https://manus.im',
    tags: ['Agent', '自动化', '通用', '自主'],
    features: ['自主网页浏览', '多步骤任务', '文件处理', '代码执行', '自我纠错'],
    pros: ['通用性最强', '自主完成复杂任务'],
    cons: ['邀请制', '价格未知', '尚在早期'],
    bestFor: '需要自动化复杂任务的高级用户',
  },
  {
    slug: 'coze', name: '扣子（Coze）', maker: '字节跳动', logo: '🤖',
    category: 'AI Agent', tagline: '字节出品AI Bot平台，无代码搭建智能体',
    desc: '字节跳动出品的 AI 应用开发平台，无代码搭建 AI Bot，支持接入各种插件和数据，可发布到豆包、微信等多渠道。',
    price: '免费', priceDetail: '基础功能免费；高级功能付费',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.3,
    url: 'https://www.coze.cn',
    tags: ['Agent', 'Bot', '无代码', '字节'],
    features: ['无代码搭建Bot', '插件市场', '多渠道发布', '知识库', '工作流'],
    pros: ['国内直连', '免费', '无代码', '发布渠道多'],
    cons: ['功能深度有限', '定制化受限'],
    bestFor: '想搭建AI应用但不会编程的创业者',
  },
  {
    slug: 'dify', name: 'Dify', maker: 'LangGenius', logo: '⚙️',
    category: 'AI Agent', tagline: '开源LLM应用开发平台，企业私有化部署',
    desc: '开源的 LLM 应用开发框架，支持可视化搭建 AI 工作流，可私有化部署，企业级安全，是技术团队构建 AI 应用的首选。',
    price: '免费', priceDetail: '开源免费自部署；云版本按用量付费',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.5,
    url: 'https://dify.ai',
    tags: ['开源', 'Agent', '企业', '私有化'],
    features: ['可视化工作流', '私有化部署', '多模型支持', '知识库RAG', 'API输出'],
    pros: ['开源可控', '企业安全', '功能完整'],
    cons: ['需要技术部署', '有学习成本'],
    bestFor: '技术团队、需要私有化AI的企业',
  },
  {
    slug: 'fastgpt', name: 'FastGPT', maker: 'FastAI', logo: '⚡',
    category: 'AI Agent', tagline: '知识库问答AI，企业智能客服首选',
    desc: '专注于知识库问答的 AI 平台，上传文档即可构建专属知识库，适合企业客服、内部知识管理、产品问答等场景。',
    price: '免费/付费', priceDetail: '开源免费；云版本按用量计费',
    hasFree: true, hasApi: true, cnAccess: true, rating: 4.3,
    url: 'https://fastgpt.in',
    tags: ['知识库', '客服', '企业', '问答'],
    features: ['知识库问答', '文档上传', 'AI客服', '工作流', 'API输出'],
    pros: ['知识库问答专业', '国内直连', '开源'],
    cons: ['需要部署配置'],
    bestFor: '企业客服、内部知识管理',
  },
  {
    slug: 'zapier', name: 'Zapier AI', maker: 'Zapier', logo: '🔗',
    category: 'AI Agent', tagline: '连接7000+应用的AI自动化平台',
    desc: '连接 7000+ 应用的自动化平台，现已加入 AI 功能，可以让 AI 决策触发不同的自动化流程，是非技术人员的自动化神器。',
    price: '免费/付费', priceDetail: '免费100任务/月；Starter $19.99/月；Professional $49/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://zapier.com',
    tags: ['自动化', '集成', 'AI决策', '无代码'],
    features: ['7000+应用集成', 'AI决策触发', '无代码自动化', 'Webhook支持', '多步骤工作流'],
    pros: ['集成最多', '无代码易用', 'AI决策智能'],
    cons: ['需要翻墙', '价格随任务量增'],
    bestFor: '非技术人员的工作流自动化',
  },

  // ══════════════════════════════════════════════════════
  // 11. AI视频剪辑
  // ══════════════════════════════════════════════════════
  {
    slug: 'capcut', name: '剪映专业版', maker: '字节跳动', logo: '✂️',
    category: 'AI剪辑', tagline: '字节出品，AI剪辑功能最强最全',
    desc: '字节跳动出品的专业视频剪辑软件，AI 功能极强：自动字幕、一键成片、AI特效、模板丰富，是国内自媒体首选剪辑工具。',
    price: '免费/付费', priceDetail: '基础功能免费；会员¥79.9/月解锁全部AI功能',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.6,
    url: 'https://www.capcut.cn',
    tags: ['剪辑', 'AI字幕', '一键成片', '模板'],
    features: ['AI自动字幕', '一键成片', 'AI特效', '抠图抠像', '变声变速'],
    pros: ['功能最全面', '免费可用', '更新快', '模板丰富'],
    cons: ['高级AI需付费'],
    bestFor: '国内自媒体创作者首选剪辑工具',
  },
  {
    slug: 'runway-edit', name: 'Runway（剪辑）', maker: 'Runway', logo: '🎬',
    category: 'AI剪辑', tagline: 'AI视频剪辑创意工具，导演级功能',
    desc: 'Runway 除视频生成外还提供专业 AI 视频编辑功能，包括 AI 背景替换、对象消除、风格迁移等导演级工具。',
    price: '付费', priceDetail: '含在Runway订阅中 $15/月起',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.4,
    url: 'https://runwayml.com',
    tags: ['剪辑', '专业', 'AI特效', '背景替换'],
    features: ['AI背景替换', '对象消除', '风格迁移', '运动追踪', '帧插值'],
    pros: ['专业特效强', '创意功能独特'],
    cons: ['需要翻墙', '价格不低'],
    bestFor: '专业视频制作者、创意广告公司',
  },

  // ══════════════════════════════════════════════════════
  // 12. AI设计工具
  // ══════════════════════════════════════════════════════
  {
    slug: 'canva', name: 'Canva AI', maker: 'Canva', logo: '🖌️',
    category: 'AI设计', tagline: '设计新手神器，AI功能越来越强',
    desc: 'Canva 已集成大量 AI 功能：AI 生图、背景移除、魔法扩图、文字效果、AI 演示生成，设计门槛极低，适合非设计师。',
    price: '免费/付费', priceDetail: '免费版功能丰富；Pro $12.99/月；Teams $14.99/人/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.5,
    url: 'https://www.canva.com',
    tags: ['设计', 'AI生图', '模板', '营销素材'],
    features: ['海量模板', 'AI生图', 'AI背景移除', '魔法扩图', '品牌套件'],
    pros: ['操作最简单', '模板最丰富', '免费可用'],
    cons: ['需要翻墙', '定制化受限'],
    bestFor: '非设计师的营销人员、内容创作者',
  },
  {
    slug: 'adobe-firefly', name: 'Adobe Firefly', maker: 'Adobe', logo: '🔥',
    category: 'AI设计', tagline: 'Adobe出品，商业授权最安全的AI生图',
    desc: 'Adobe 出品的 AI 生图工具，训练数据来自 Adobe Stock 授权图片，商业使用无版权风险，深度整合在 Photoshop 等 CC 应用中。',
    price: '付费', priceDetail: '含在Adobe CC订阅中；独立版 $4.99/月',
    hasFree: true, hasApi: false, cnAccess: false, rating: 4.3,
    url: 'https://firefly.adobe.com',
    tags: ['设计', 'AI生图', '商业授权', 'Photoshop'],
    features: ['商业授权安全', 'Photoshop集成', '生成填充', '文字效果', '风格参考'],
    pros: ['商业授权最安全', 'Adobe生态集成'],
    cons: ['需要Adobe订阅', '质量不如Midjourney'],
    bestFor: '专业设计师、需要商业授权保障的企业',
  },
  {
    slug: 'gaoding', name: '稿定设计', maker: '稿定科技', logo: '📐',
    category: 'AI设计', tagline: '国内设计平台，AI功能快速迭代',
    desc: '国内优质设计平台，提供海量模板，AI 生图、AI 抠图、AI 设计等功能快速更新，价格实惠，国内直连。',
    price: '免费/付费', priceDetail: '基础免费；会员¥49/月',
    hasFree: true, hasApi: false, cnAccess: true, rating: 4.2,
    url: 'https://www.gaoding.com',
    tags: ['设计', '国内', '模板', 'AI生图'],
    features: ['海量中文模板', 'AI生图', 'AI抠图', '视频模板', '品牌设计'],
    pros: ['国内直连', '中文模板多', '价格实惠'],
    cons: ['质量弱于Canva'],
    bestFor: '国内电商商家、内容创作者',
  },

  // ══════════════════════════════════════════════════════
  // 补全：工作流组合中用到但缺详情页的工具（25个）
  // ══════════════════════════════════════════════════════

  {
    slug: 'codeium', name: 'Codeium', maker: 'Exafunction', logo: '💚',
    category: 'AI编程', tagline: '完全免费的AI代码补全，Copilot的最佳平替',
    desc: 'Codeium 是一款完全免费的AI编程助手，支持VS Code、JetBrains等70+IDE，代码补全速度快、准确率高，对个人开发者永久免费，是GitHub Copilot的最强免费替代。',
    price: '免费', priceDetail: '个人永久免费，企业版$12/人/月',
    pricePlans: [
      { name: '个人版', price: '$0', period: '/月', features: ['无限代码补全', '70+IDE支持', '所有语言支持', '永久免费'], highlight: true },
      { name: '企业版', price: '$12', period: '/人/月', features: ['全部个人功能', '私有代码安全', '企业SSO', '审计日志'] },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 2, rating: 4.5, ratingCount: 1680,
    url: 'https://codeium.com',
    tags: ['AI编程', '代码补全', '免费', 'VS Code', 'IDE'],
    features: ['实时代码补全', '多行代码生成', '智能重构建议', '聊天式问答', '70+IDE集成'],
    pros: ['完全免费无限制', '速度比Copilot更快', '国内可直接访问', '支持更多IDE'],
    cons: ['对话功能弱于Cursor', '复杂代码理解力略逊', '无项目级代码库分析'],
    bestFor: '预算有限的学生和独立开发者',
    tutorials: [
      { title: 'Codeium免费AI代码补全安装与使用教程', url: 'https://search.bilibili.com/all?keyword=Codeium使用教程', platform: 'bilibili', duration: '10分钟', level: 'beginner' },
    ],
    useCases: ['日常代码补全', '学习编程辅助', 'Python/JS开发', '重构优化', '代码注释生成'],
    compareWith: ['cursor', 'github-copilot'],
  },

  {
    slug: 'obsidian', name: 'Obsidian', maker: 'Obsidian', logo: '💎',
    category: '知识管理', tagline: '本地双链笔记神器，知识工作者必备',
    desc: 'Obsidian 是一款基于本地Markdown文件的双链笔记软件，支持知识图谱可视化，数据完全存储在本地，隐私安全。搭配AI插件可实现智能问答，是知识工作者和研究人员的首选工具。',
    price: '免费', priceDetail: '个人完全免费，商业使用$50/年，同步服务$8/月',
    pricePlans: [
      { name: '个人版', price: '$0', period: '/月', features: ['全部核心功能', '本地数据存储', '1000+社区插件', 'iOS/Android'], highlight: true },
      { name: 'Sync', price: '$8', period: '/月', features: ['端对端加密同步', '版本历史', '多设备同步'] },
      { name: '商业版', price: '$50', period: '/年', features: ['商业使用授权', '所有个人功能'] },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 3, rating: 4.6, ratingCount: 2100,
    url: 'https://obsidian.md',
    tags: ['笔记', '知识管理', '双链', 'Markdown', '本地存储'],
    features: ['双向链接', '知识图谱可视化', 'Markdown编辑', '1000+插件', '本地数据存储', 'AI插件支持'],
    pros: ['数据完全本地化隐私安全', '双链笔记构建知识图谱', '插件生态极其丰富', '永久免费使用'],
    cons: ['上手有一定学习曲线', '实时协作功能弱', '同步需额外付费', '移动端体验一般'],
    bestFor: '研究人员、知识工作者、重视数据隐私的用户',
    tutorials: [
      { title: 'Obsidian新手完整入门教程：从安装到用法', url: 'https://search.bilibili.com/all?keyword=Obsidian新手入门教程', platform: 'bilibili', duration: '20分钟', level: 'beginner' },
      { title: 'Obsidian+AI插件：打造智能个人知识库', url: 'https://search.bilibili.com/all?keyword=Obsidian+AI插件', platform: 'bilibili', duration: '25分钟', level: 'advanced' },
    ],
    useCases: ['学术研究笔记', '读书笔记整理', '项目管理', '个人知识库', '写作素材库'],
    compareWith: ['notion-ai'],
  },

  {
    slug: 'vercel', name: 'Vercel', maker: 'Vercel Inc.', logo: '▲',
    category: '开发工具', tagline: '前端部署神器，从代码到上线只需1分钟',
    desc: 'Vercel 是面向前端开发者的云部署平台，与GitHub深度集成，推送代码自动构建部署，免费套餐对个人项目完全够用。Next.js官方推荐部署平台，全球CDN加速，支持Serverless函数。',
    price: '免费起', priceDetail: '个人免费，Pro $20/月，Enterprise企业定价',
    pricePlans: [
      { name: 'Hobby', price: '$0', period: '/月', features: ['无限个人项目', '100GB流量/月', '自动HTTPS', 'GitHub集成', 'Serverless函数'], highlight: true },
      { name: 'Pro', price: '$20', period: '/月', features: ['商业项目支持', '1TB流量', '团队协作', '高级分析', '更多并发'] },
    ],
    hasFree: true, hasApi: true, cnAccess: true, difficulty: 2, rating: 4.7, ratingCount: 2450,
    url: 'https://vercel.com',
    tags: ['部署', '前端', 'Next.js', 'CDN', 'Serverless'],
    features: ['Git推送自动部署', '全球CDN加速', 'Serverless函数', '自定义域名', '预览部署', '分析监控'],
    pros: ['部署极简一键完成', 'Next.js最佳搭档', '免费额度非常慷慨', '国内访问速度尚可'],
    cons: ['国内访问偶有波动', '大流量费用较高', '不适合纯后端项目', '免费版有带宽限制'],
    bestFor: '独立开发者、前端工程师、Next.js项目',
    tutorials: [
      { title: 'Vercel部署教程：5分钟上线你的网站', url: 'https://search.bilibili.com/all?keyword=Vercel部署教程', platform: 'bilibili', duration: '8分钟', level: 'beginner' },
      { title: 'Vercel+GitHub自动化CI/CD完整配置', url: 'https://www.youtube.com/results?search_query=vercel+github+deployment+tutorial+2025', platform: 'youtube', duration: '15分钟', level: 'advanced' },
    ],
    useCases: ['Next.js项目部署', 'React应用上线', '静态网站托管', 'API接口部署', 'MVP快速上线'],
    compareWith: ['bolt', 'cursor'],
  },

  {
    slug: 'supabase', name: 'Supabase', maker: 'Supabase Inc.', logo: '🗄️',
    category: '开发工具', tagline: '开源Firebase替代，免费PostgreSQL数据库',
    desc: 'Supabase 是开源的Firebase替代品，提供PostgreSQL数据库、身份验证、实时订阅、文件存储等一站式后端服务。免费套餐包含500MB数据库，是独立开发者构建MVP的首选后端平台。',
    price: '免费起', priceDetail: '免费500MB数据库，Pro $25/月含8GB',
    pricePlans: [
      { name: '免费版', price: '$0', period: '/月', features: ['2个项目', '500MB数据库', '1GB文件存储', '50MB带宽', 'Auth认证'], highlight: true },
      { name: 'Pro', price: '$25', period: '/月', features: ['无限项目', '8GB数据库', '100GB存储', '250GB带宽', '每日备份'] },
    ],
    hasFree: true, hasApi: true, cnAccess: true, difficulty: 3, rating: 4.5, ratingCount: 1320,
    url: 'https://supabase.com',
    tags: ['数据库', 'PostgreSQL', '后端', 'Firebase替代', '开源'],
    features: ['PostgreSQL数据库', '用户身份验证', '实时数据订阅', '文件存储', 'Edge Functions', 'REST/GraphQL API'],
    pros: ['免费额度对MVP完全够用', '开源可自部署', '与Vercel/Next.js无缝集成', 'PostgreSQL全功能'],
    cons: ['免费项目闲置7天会暂停', '国内访问速度一般', '需要一定数据库基础', '复杂查询性能不如专业数据库'],
    bestFor: '独立开发者、构建MVP的创业团队',
    tutorials: [
      { title: 'Supabase入门教程：免费数据库快速上手', url: 'https://search.bilibili.com/all?keyword=Supabase教程', platform: 'bilibili', duration: '15分钟', level: 'beginner' },
      { title: 'Supabase+Next.js全栈开发完整教程', url: 'https://www.youtube.com/results?search_query=supabase+nextjs+tutorial+2025', platform: 'youtube', duration: '30分钟', level: 'advanced' },
    ],
    useCases: ['用户注册登录系统', 'MVP后端搭建', '实时聊天应用', '数据管理后台', '文件上传存储'],
    compareWith: ['dify', 'fastgpt'],
  },

  {
    slug: 'shopify', name: 'Shopify', maker: 'Shopify Inc.', logo: '🛍️',
    category: '电商工具', tagline: '全球最大独立站建站平台，跨境电商首选',
    desc: 'Shopify 是全球领先的电商建站平台，支持快速搭建独立站，内置支付、库存、物流管理，集成数千款营销插件。目前全球有超过200万商家使用，是跨境电商卖家的标准配置。',
    price: '$39/月起', priceDetail: 'Basic $39/月，Shopify $105/月，Advanced $399/月，均含14天免费试用',
    pricePlans: [
      { name: 'Basic', price: '$39', period: '/月', features: ['完整在线商店', '无限商品', '2个员工账号', '基础报表', '2%额外手续费'] },
      { name: 'Shopify', price: '$105', period: '/月', features: ['所有Basic功能', '5个员工账号', '详细报表', '1%手续费'], highlight: true },
      { name: 'Advanced', price: '$399', period: '/月', features: ['15个员工账号', '高级报表', '第三方计算运费', '0.5%手续费'] },
    ],
    hasFree: false, hasApi: true, cnAccess: true, difficulty: 3, rating: 4.4, ratingCount: 1890,
    url: 'https://www.shopify.com',
    tags: ['电商', '独立站', '跨境', '建站', 'DTC'],
    features: ['一键建站', '多货币支付', '库存管理', '废弃购物车挽回', 'SEO优化', 'Shopify Payments'],
    pros: ['生态最成熟插件最多', '多货币多语言支持', '内置SEO工具', '与Facebook/Google广告深度集成'],
    cons: ['月费相对较高', '交易手续费叠加成本', '高度定制需要开发能力', '国内支付集成复杂'],
    bestFor: '有稳定销量的跨境电商卖家、DTC品牌',
    tutorials: [
      { title: 'Shopify独立站从零建站完整教程2025', url: 'https://search.bilibili.com/all?keyword=Shopify独立站教程2025', platform: 'bilibili', duration: '40分钟', level: 'beginner' },
      { title: 'Shopify高级运营：广告+邮件+SEO完整体系', url: 'https://www.youtube.com/results?search_query=shopify+marketing+tutorial+2025', platform: 'youtube', duration: '45分钟', level: 'advanced' },
    ],
    useCases: ['跨境独立站建设', 'DTC品牌官网', '多SKU商品管理', '多国家市场拓展', '直播带货独立站'],
    compareWith: ['helium10'],
  },

  {
    slug: 'klaviyo', name: 'Klaviyo', maker: 'Klaviyo Inc.', logo: '📧',
    category: '电商工具', tagline: '独立站邮件营销自动化，ROI最高的增长工具',
    desc: 'Klaviyo 是专为电商设计的邮件+短信营销自动化平台，与Shopify深度集成，支持基于用户行为的精准触发营销。平均为商家带来30倍投资回报，是独立站提升复购率的核心工具。',
    price: '$30/月起', priceDetail: '免费版支持250联系人，付费版按联系人数量计费',
    pricePlans: [
      { name: '免费版', price: '$0', period: '/月', features: ['250联系人', '500封邮件/月', '150条短信', '基础自动化'] },
      { name: '邮件版', price: '$30', period: '/月起', features: ['1000+联系人', '无限发送', '所有自动化流程', 'A/B测试'], highlight: true },
      { name: '邮件+短信', price: '$45', period: '/月起', features: ['邮件全功能', '短信营销', '多渠道归因分析'] },
    ],
    hasFree: true, hasApi: true, cnAccess: false, difficulty: 3, rating: 4.3, ratingCount: 890,
    url: 'https://www.klaviyo.com',
    tags: ['邮件营销', '电商', 'Shopify', '自动化', '独立站'],
    features: ['废弃购物车邮件', '用户行为触发', 'A/B测试', '短信营销', '细分人群', '多渠道归因'],
    pros: ['与Shopify集成最深', '行为触发自动化强', 'ROI极高平均30倍', '数据分析详细'],
    cons: ['需要梯子才能访问', '联系人多时费用较高', '学习曲线较陡', '仅适合独立站场景'],
    bestFor: '有稳定用户基础的Shopify独立站卖家',
    tutorials: [
      { title: 'Klaviyo邮件营销完整教程：废弃购物车+欢迎序列', url: 'https://www.youtube.com/results?search_query=klaviyo+email+marketing+tutorial+2025', platform: 'youtube', duration: '35分钟', level: 'beginner' },
    ],
    useCases: ['废弃购物车挽回', '新用户欢迎序列', '复购提醒', '节日促销', '用户分层运营'],
    compareWith: ['shopify', 'helium10'],
  },

  {
    slug: 'audacity', name: 'Audacity', maker: 'Audacity Team', logo: '🎵',
    category: '音频工具', tagline: '免费开源专业录音剪辑，播客制作必备',
    desc: 'Audacity 是历史最悠久的免费开源音频编辑软件，支持Windows/Mac/Linux，功能覆盖录音、降噪、剪辑、混音、格式转换。尽管界面老旧，但功能完整，是播客新手的最佳起步工具。',
    price: '免费开源', priceDetail: '完全免费，永久开源，无任何付费功能',
    pricePlans: [
      { name: '免费版', price: '$0', period: '永久', features: ['完整录音功能', '噪音消除', '多轨剪辑', '格式转换', '跨平台支持'], highlight: true },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 3, rating: 4.1, ratingCount: 1560,
    url: 'https://www.audacityteam.org',
    tags: ['录音', '音频编辑', '播客', '开源', '免费'],
    features: ['多轨录音', 'AI噪音消除', '音频剪辑', '效果器', '格式转换（MP3/WAV/FLAC）', '频谱分析'],
    pros: ['完全免费永久可用', '功能覆盖专业需求', '跨平台Windows/Mac/Linux', '社区教程丰富'],
    cons: ['界面设计较为老旧', '实时监听延迟稍高', '不支持非破坏性编辑', 'AI功能不如新工具'],
    bestFor: '播客新手、学生、预算有限的音频创作者',
    tutorials: [
      { title: 'Audacity新手完整教程：录音+降噪+剪辑', url: 'https://search.bilibili.com/all?keyword=Audacity使用教程', platform: 'bilibili', duration: '20分钟', level: 'beginner' },
      { title: 'Audacity播客制作：从录音到发布完整流程', url: 'https://www.youtube.com/results?search_query=audacity+podcast+tutorial+2025', platform: 'youtube', duration: '25分钟', level: 'advanced' },
    ],
    useCases: ['播客录制', '声音降噪处理', '音频格式转换', '配音剪辑', '音乐demo录制'],
    compareWith: ['descript', 'elevenlabs'],
  },

  {
    slug: 'adobe-audition', name: 'Adobe Audition', maker: 'Adobe', logo: '🎚️',
    category: '音频工具', tagline: '行业标准专业音频制作工具，精品播客必备',
    desc: 'Adobe Audition 是广播、播客、影视行业标准的专业音频编辑软件，提供多轨混音、频谱修复、降噪、母带处理等专业功能。与Premiere Pro无缝集成，适合需要专业音质的内容创作者。',
    price: '¥168/月', priceDetail: '单独订阅¥168/月，Creative Cloud全套¥399/月',
    pricePlans: [
      { name: '单独版', price: '¥168', period: '/月', features: ['完整Audition功能', '100GB云存储', 'Adobe Fonts', '更新保障'] },
      { name: 'CC全套', price: '¥399', period: '/月', features: ['所有Adobe应用', '100GB云存储', 'Premiere+PS等全套'], highlight: true },
    ],
    hasFree: false, hasApi: false, cnAccess: true, difficulty: 4, rating: 4.3, ratingCount: 780,
    url: 'https://www.adobe.com/products/audition.html',
    tags: ['专业音频', '混音', '播客', 'Adobe', '广播'],
    features: ['多轨混音', '频谱修复', 'AI降噪', '母带处理', 'Premiere集成', 'VST插件支持'],
    pros: ['行业标准专业工具', 'AI降噪效果顶级', '与Adobe生态无缝协作', '音质处理最专业'],
    cons: ['订阅费用较高', '学习曲线较陡', '非Adobe用户集成性差', '功能对新手过于复杂'],
    bestFor: '专业播客主、影视音效师、广播从业者',
    tutorials: [
      { title: 'Adobe Audition播客制作完整教程', url: 'https://search.bilibili.com/all?keyword=Adobe+Audition播客教程', platform: 'bilibili', duration: '30分钟', level: 'beginner' },
    ],
    useCases: ['广播级播客制作', '影视音效处理', '音乐混音母带', '声音设计', '多语言配音后期'],
    compareWith: ['descript', 'audacity'],
  },

  {
    slug: 'buzzsprout', name: 'Buzzsprout', maker: 'Buzzsprout', logo: '📡',
    category: '音频工具', tagline: '播客托管一键分发，20+平台自动上传',
    desc: 'Buzzsprout 是最受欢迎的播客托管和分发平台，支持一键分发到Spotify、Apple Podcasts、Google Podcasts等20+主流平台，提供详细的播客分析数据，是英文播客创作者的标准选择。',
    price: '$12/月起', priceDetail: '免费版限2小时/月，付费版$12起不限上传',
    pricePlans: [
      { name: '免费版', price: '$0', period: '/月', features: ['2小时/月', '90天存储', '基础统计', '自动分发'] },
      { name: '$12套餐', price: '$12', period: '/月', features: ['3小时/月', '永久存储', '详细统计', '章节标记'], highlight: true },
      { name: '$18套餐', price: '$18', period: '/月', features: ['6小时/月', '所有$12功能', '更多存储空间'] },
    ],
    hasFree: true, hasApi: false, cnAccess: false, difficulty: 1, rating: 4.2, ratingCount: 560,
    url: 'https://www.buzzsprout.com',
    tags: ['播客', '托管', '分发', 'Spotify', 'Apple Podcasts'],
    features: ['20+平台自动分发', '播客数据分析', '章节标记', '转录字幕', '播客网站生成', '嵌入播放器'],
    pros: ['一键分发20+平台', '界面操作极简单', '数据统计详细', '客服响应快'],
    cons: ['需要梯子访问', '免费版每月只有2小时', '功能相比对手较少', '国内平台不支持'],
    bestFor: '做英文播客的创作者、面向海外受众的播客主',
    tutorials: [
      { title: 'Buzzsprout播客发布完整教程：上传到Spotify', url: 'https://www.youtube.com/results?search_query=buzzsprout+podcast+tutorial+2025', platform: 'youtube', duration: '15分钟', level: 'beginner' },
    ],
    useCases: ['英文播客发布', '多平台自动分发', '播客数据分析', '播客网站搭建', '听众增长追踪'],
    compareWith: ['descript'],
  },

  {
    slug: 'tidio', name: 'Tidio AI', maker: 'Tidio', logo: '🤝',
    category: '电商工具', tagline: 'AI客服机器人，自动处理80%买家询问',
    desc: 'Tidio 是专为电商设计的AI客服工具，可嵌入网站和Shopify，内置Lyro AI可自动回复80%的常见客服问题，支持多语言，24小时不间断服务，显著降低人工客服成本。',
    price: '$29/月起', priceDetail: '免费版50次对话/月，付费版$29起无限对话',
    pricePlans: [
      { name: '免费版', price: '$0', period: '/月', features: ['50次AI对话/月', '基础聊天功能', '1个坐席', '邮件支持'] },
      { name: 'Starter', price: '$29', period: '/月', features: ['100次Lyro AI对话', '3个坐席', '实时聊天', 'Shopify集成'], highlight: true },
      { name: 'Growth', price: '$59', period: '/月', features: ['250次AI对话', '所有渠道集成', '高级报表', '无限坐席'] },
    ],
    hasFree: true, hasApi: true, cnAccess: false, difficulty: 2, rating: 4.2, ratingCount: 670,
    url: 'https://www.tidio.com',
    tags: ['AI客服', '电商', 'Shopify', '聊天机器人', '自动化'],
    features: ['Lyro AI自动回复', 'Shopify深度集成', '多语言支持', '访客行为追踪', '退款处理自动化', '数据分析'],
    pros: ['AI自动处理80%询问', 'Shopify集成一键安装', '多语言24小时在线', '降低人工客服成本'],
    cons: ['需要梯子才能访问', '高级AI功能额度有限', '国内买家使用习惯不同', '复杂问题仍需人工介入'],
    bestFor: '跨境独立站卖家、需要降低客服成本的电商商家',
    tutorials: [
      { title: 'Tidio AI客服配置教程：Shopify一键安装', url: 'https://www.youtube.com/results?search_query=tidio+ai+chatbot+shopify+tutorial', platform: 'youtube', duration: '15分钟', level: 'beginner' },
    ],
    useCases: ['自动回复买家询问', '退款退换货处理', '商品推荐导购', '订单状态查询', '多语言客服'],
    compareWith: ['shopify', 'helium10'],
  },

  {
    slug: 'adcreative', name: 'AdCreative.ai', maker: 'AdCreative.ai', logo: '🎯',
    category: '电商工具', tagline: 'AI广告素材生成，高转化率广告图批量产出',
    desc: 'AdCreative.ai 使用AI自动生成高转化率的广告素材，支持Facebook、Google、Instagram等主流广告平台尺寸，通过分析数百万条历史广告数据优化设计，帮助卖家快速产出A/B测试素材。',
    price: '$29/月起', priceDetail: 'Starter $29/月生成10个素材，Pro $59/月无限制',
    pricePlans: [
      { name: 'Starter', price: '$29', period: '/月', features: ['10个广告素材/月', '多平台尺寸', 'AI文案建议', '品牌套件'] },
      { name: 'Professional', price: '$59', period: '/月', features: ['无限素材生成', '所有广告格式', 'A/B测试分析', '竞品分析'], highlight: true },
    ],
    hasFree: false, hasApi: true, cnAccess: false, difficulty: 2, rating: 4.1, ratingCount: 450,
    url: 'https://www.adcreative.ai',
    tags: ['广告', '营销', 'AI设计', '电商', 'Facebook广告'],
    features: ['AI广告图生成', '多平台尺寸适配', '高转化率优化', '批量生成', '品牌资产管理', 'A/B测试'],
    pros: ['批量生成节省大量时间', 'AI优化转化率更高', '多平台尺寸一键适配', '非设计师也能用'],
    cons: ['需要梯子访问', '月费对小卖家偏高', '创意自由度受限', '需要一定广告经验配合使用'],
    bestFor: '跨境电商广告投手、DTC品牌营销团队',
    tutorials: [
      { title: 'AdCreative.ai教程：AI批量生成Facebook广告素材', url: 'https://www.youtube.com/results?search_query=adcreative+ai+tutorial+2025', platform: 'youtube', duration: '12分钟', level: 'beginner' },
    ],
    useCases: ['Facebook广告素材', 'Google展示广告', 'Instagram广告', '商品主图测试', '节日促销素材'],
    compareWith: ['shopify', 'canva'],
  },

  {
    slug: 'comfyui', name: 'ComfyUI', maker: '社区开源', logo: '⚙️',
    category: 'AI绘画', tagline: '本地Stable Diffusion工作流，专业级图像生成',
    desc: 'ComfyUI 是基于节点的Stable Diffusion图形化工作流工具，通过拖拽节点构建复杂的AI绘画管线，支持LoRA、ControlNet等高级功能，完全本地运行，无需月费，是专业AI绘画从业者的首选。',
    price: '免费开源', priceDetail: '软件免费，需要本地GPU（推荐8GB+显存）运行',
    pricePlans: [
      { name: '本地部署', price: '¥0', period: '软件免费', features: ['完全免费使用', '无次数限制', '支持所有SD模型', '可商用'], highlight: true },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 5, rating: 4.4, ratingCount: 1200,
    url: 'https://github.com/comfyanonymous/ComfyUI',
    tags: ['AI绘画', 'Stable Diffusion', '本地', 'LoRA', '开源'],
    features: ['节点式工作流', 'ControlNet支持', 'LoRA微调', '批量生图', '自定义模型', 'API接口'],
    pros: ['完全免费无次数限制', '工作流高度可定制', '支持所有开源模型', '本地运行隐私安全'],
    cons: ['需要独立显卡（8GB+显存）', '学习曲线极陡', '需要手动安装配置', '技术门槛最高'],
    bestFor: '有技术背景的专业AI绘画创作者、研究者',
    tutorials: [
      { title: 'ComfyUI安装教程：从零搭建本地AI绘画环境', url: 'https://search.bilibili.com/all?keyword=ComfyUI安装教程', platform: 'bilibili', duration: '30分钟', level: 'beginner' },
      { title: 'ComfyUI高级工作流：ControlNet+LoRA实战', url: 'https://search.bilibili.com/all?keyword=ComfyUI高级工作流', platform: 'bilibili', duration: '45分钟', level: 'advanced' },
    ],
    useCases: ['商业AI绘画接单', '角色一致性生成', 'LoRA模型训练', '批量商品图', '视频帧处理'],
    compareWith: ['midjourney', 'stable-diffusion', 'jimeng'],
  },

  {
    slug: 'beautiful-ai', name: 'Beautiful.ai', maker: 'Beautiful.ai', logo: '💎',
    category: 'PPT工具', tagline: 'AI自动对齐布局，设计感极强的演示文稿',
    desc: 'Beautiful.ai 使用AI智能布局引擎，在你添加内容时自动调整排版使其保持美观，无需手动对齐。内置数百个专业模板，特别适合需要快速制作高质感商业演示文稿的职场人。',
    price: '$12/月', priceDetail: 'Pro $12/月，Team $40/人/月，Enterprise企业定价',
    pricePlans: [
      { name: 'Pro', price: '$12', period: '/月', features: ['无限演示文稿', '60+智能模板', 'PDF/PPT导出', '自定义品牌'], highlight: true },
      { name: 'Team', price: '$40', period: '/人/月', features: ['所有Pro功能', '团队协作', '品牌管理', '分析统计'] },
    ],
    hasFree: false, hasApi: false, cnAccess: false, difficulty: 1, rating: 4.2, ratingCount: 680,
    url: 'https://www.beautiful.ai',
    tags: ['PPT', '演示', 'AI设计', '商务', '自动排版'],
    features: ['AI智能布局', '自动对齐排版', '动态数据图表', 'GIF动画支持', '团队协作', 'PPT/PDF导出'],
    pros: ['AI自动排版始终美观', '上手简单无需设计基础', '模板质量高', '导出格式多'],
    cons: ['需要梯子访问', '自定义自由度低于PowerPoint', '模板风格有局限', '月费较高'],
    bestFor: '需要快速出高质量PPT的职场人、创业者',
    tutorials: [
      { title: 'Beautiful.ai使用教程：AI自动排版PPT', url: 'https://www.youtube.com/results?search_query=beautiful+ai+presentation+tutorial', platform: 'youtube', duration: '12分钟', level: 'beginner' },
    ],
    useCases: ['商务提案PPT', '项目汇报', '销售演示', '投资路演', '培训课件'],
    compareWith: ['gamma', 'aippt', 'tome'],
  },

  {
    slug: 'premiere-pro', name: 'Premiere Pro', maker: 'Adobe', logo: '🎞️',
    category: '视频工具', tagline: '好莱坞级专业视频剪辑，AI功能持续进化',
    desc: 'Adobe Premiere Pro 是全球使用最广泛的专业视频剪辑软件，内置AI自动字幕、语音增强、色彩匹配等功能。与After Effects、Audition无缝协作，是影视、广告、YouTube创作者的行业标准工具。',
    price: '¥168/月', priceDetail: '单独订阅¥168/月，Creative Cloud全套¥399/月',
    pricePlans: [
      { name: '单独版', price: '¥168', period: '/月', features: ['完整PR功能', '100GB云存储', 'AI自动字幕', '更新保障'] },
      { name: 'CC全套', price: '¥399', period: '/月', features: ['所有Adobe应用', 'PR+AE+PS+AU全套', '100GB云存储'], highlight: true },
    ],
    hasFree: false, hasApi: false, cnAccess: true, difficulty: 4, rating: 4.4, ratingCount: 1650,
    url: 'https://www.adobe.com/products/premiere.html',
    tags: ['视频剪辑', '专业', 'Adobe', '影视', 'YouTube'],
    features: ['多轨时间线剪辑', 'AI自动字幕', 'Lumetri色彩', '代理剪辑', 'After Effects集成', 'AI语音增强'],
    pros: ['行业标准兼容性最好', 'AI功能持续更新强化', 'Adobe生态协作流畅', '支持4K/8K专业格式'],
    cons: ['订阅费用较高', '学习曲线较陡', '对硬件配置要求高', '功能对短视频创作者过于复杂'],
    bestFor: '影视从业者、专业YouTuber、广告视频制作团队',
    tutorials: [
      { title: 'Premiere Pro新手入门教程：从剪辑到导出', url: 'https://search.bilibili.com/all?keyword=Premiere+Pro新手教程', platform: 'bilibili', duration: '30分钟', level: 'beginner' },
      { title: 'PR高级技巧：AI字幕+色彩分级+After Effects联动', url: 'https://search.bilibili.com/all?keyword=Premiere+Pro高级技巧', platform: 'bilibili', duration: '40分钟', level: 'advanced' },
    ],
    useCases: ['影视广告制作', 'YouTube长视频', '品牌宣传片', '婚礼MV', '纪录片剪辑'],
    compareWith: ['capcut', 'davinci-resolve'],
  },

  {
    slug: 'davinci-resolve', name: 'DaVinci Resolve', maker: 'Blackmagic Design', logo: '✂️',
    category: '视频工具', tagline: '专业调色剪辑免费版，好莱坞级调色工具',
    desc: 'DaVinci Resolve 是由Blackmagic Design出品的专业视频剪辑和调色软件，免费版功能已经超过大多数付费软件，特别是调色功能被誉为行业最佳。Netflix、好莱坞大片普遍使用其进行后期制作。',
    price: '免费', priceDetail: '免费版功能完整，Studio版$295一次性买断',
    pricePlans: [
      { name: '免费版', price: '$0', period: '永久', features: ['完整剪辑功能', '顶级调色工具', 'Fusion特效', 'Fairlight音频', '4K支持'], highlight: true },
      { name: 'Studio版', price: '$295', period: '买断', features: ['所有免费功能', '协同剪辑', 'AI工具增强', '4K+以上分辨率'] },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 4, rating: 4.6, ratingCount: 1980,
    url: 'https://www.blackmagicdesign.com/products/davinciresolve',
    tags: ['视频剪辑', '调色', '免费', '专业', '好莱坞'],
    features: ['专业调色面板', '多轨剪辑', 'Fusion视觉特效', 'Fairlight混音', 'AI魔法遮罩', '协同制作'],
    pros: ['免费版功能极其完整', '调色工具行业最强', '一次买断无订阅', '好莱坞同款工具'],
    cons: ['学习曲线陡峭', '对硬件要求高', '界面复杂对新手不友好', '部分高级功能需Studio版'],
    bestFor: '追求专业调色的视频创作者、影视后期制作人员',
    tutorials: [
      { title: 'DaVinci Resolve新手入门：专业调色从零开始', url: 'https://search.bilibili.com/all?keyword=DaVinci+Resolve教程', platform: 'bilibili', duration: '35分钟', level: 'beginner' },
    ],
    useCases: ['电影级调色', '纪录片后期', '广告片制作', '婚礼视频', 'MV制作'],
    compareWith: ['capcut', 'premiere-pro'],
  },

  {
    slug: 'yixiaoer', name: '蚁小二', maker: '蚁小二科技', logo: '📱',
    category: '内容工具', tagline: '国内多平台内容分发，一键同步抖音小红书',
    desc: '蚁小二是国内专业的多平台内容分发工具，支持一键将内容同步发布到抖音、快手、小红书、微信视频号、B站等主流平台，同时提供内容日历管理和数据统计功能，帮助自媒体提升运营效率。',
    price: '¥49/月起', priceDetail: '基础版¥49/月，专业版¥99/月，企业版另议',
    pricePlans: [
      { name: '基础版', price: '¥49', period: '/月', features: ['5个平台同步', '50次/月发布', '基础数据统计', '内容日历'] },
      { name: '专业版', price: '¥99', period: '/月', features: ['10个平台同步', '无限次发布', '详细数据分析', '团队协作'], highlight: true },
    ],
    hasFree: false, hasApi: false, cnAccess: true, difficulty: 1, rating: 4.0, ratingCount: 380,
    url: 'https://www.yixiaoer.cn',
    tags: ['多平台分发', '自媒体', '国内', '内容运营', '自动化'],
    features: ['10+平台一键分发', '内容日历管理', '数据聚合统计', '定时发布', '素材云存储'],
    pros: ['国内直连操作简单', '多平台一键同步节省时间', '数据聚合统一管理', '适合国内自媒体'],
    cons: ['月费对个人较贵', '功能相比海外工具较基础', '海外平台支持不完善', '部分平台需手动授权'],
    bestFor: '同时运营多个国内社交平台的自媒体创作者',
    tutorials: [
      { title: '蚁小二使用教程：一键同步多平台内容', url: 'https://search.bilibili.com/all?keyword=蚁小二使用教程', platform: 'bilibili', duration: '8分钟', level: 'beginner' },
    ],
    useCases: ['多平台内容同步', '自媒体矩阵运营', '定时发布内容', '内容数据统一查看', '团队协作发布'],
    compareWith: ['capcut'],
  },

  {
    slug: 'xiaoyuzhou', name: '小宇宙', maker: '字节跳动', logo: '🎧',
    category: '音频工具', tagline: '国内最大播客平台，中文播客发布首选',
    desc: '小宇宙是由字节跳动旗下的国内最大播客平台，为播客主提供音频上传、节目管理、数据统计等服务，同时拥有活跃的播客社区。国内中文播客发布必选平台，用户基础最大。',
    price: '免费', priceDetail: '创作者发布播客完全免费，无需付费',
    pricePlans: [
      { name: '创作者版', price: '¥0', period: '永久免费', features: ['无限音频上传', '数据统计', '节目管理', '听众互动', '多节目管理'], highlight: true },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 1, rating: 4.3, ratingCount: 1100,
    url: 'https://www.xiaoyuzhoufm.com',
    tags: ['播客', '国内', '音频', '社区', '中文'],
    features: ['播客托管上传', '节目数据统计', '听众留言互动', '分章节管理', '多节目管理', 'App内播放'],
    pros: ['国内用户基础最大', '完全免费无限上传', '字节系流量支持', '社区氛围活跃'],
    cons: ['海外收听不方便', '货币化变现功能较弱', '数据统计不如海外平台详细', '国际分发需额外工具'],
    bestFor: '面向国内听众的中文播客创作者',
    tutorials: [
      { title: '小宇宙播客发布教程：从录音到上线全流程', url: 'https://search.bilibili.com/all?keyword=小宇宙播客发布教程', platform: 'bilibili', duration: '10分钟', level: 'beginner' },
    ],
    useCases: ['中文播客发布', '国内听众运营', '知识付费音频', '节目系列管理', '播客数据分析'],
    compareWith: ['descript', 'audacity'],
  },

  {
    slug: 'yuque', name: '语雀', maker: '阿里巴巴', logo: '🦆',
    category: '知识管理', tagline: '阿里出品国内协作文档，企业知识库首选',
    desc: '语雀是阿里巴巴出品的专业知识管理与协作平台，支持文档、表格、思维导图等多种内容形式，提供团队知识库、文档协作、权限管理等企业级功能。已被大量中国互联网公司采用作为内部知识管理工具。',
    price: '免费', priceDetail: '个人免费，团队版¥99/人/年，企业版另议',
    pricePlans: [
      { name: '个人版', price: '¥0', period: '/月', features: ['无限文档', '100MB存储', '基础协作', '公开知识库'], highlight: true },
      { name: '团队版', price: '¥99', period: '/人/年', features: ['无限存储', '高级权限', '数据备份', '企业SSO'] },
    ],
    hasFree: true, hasApi: true, cnAccess: true, difficulty: 1, rating: 4.3, ratingCount: 1450,
    url: 'https://www.yuque.com',
    tags: ['知识管理', '文档协作', '国内', '阿里', '企业'],
    features: ['富文本文档编辑', '思维导图', '表格数据', '协作评论', '版本历史', '知识库组织'],
    pros: ['国内直连访问稳定', '免费功能完整', '支持多种内容格式', '企业知识库管理成熟'],
    cons: ['AI功能相对较弱', '国际化支持差', '免费存储容量有限', '离线功能较弱'],
    bestFor: '国内团队协作、企业知识沉淀、个人学习笔记',
    tutorials: [
      { title: '语雀使用教程：从个人笔记到团队知识库', url: 'https://search.bilibili.com/all?keyword=语雀使用教程', platform: 'bilibili', duration: '12分钟', level: 'beginner' },
    ],
    useCases: ['团队文档协作', '企业知识库建设', '技术文档管理', '学习笔记整理', '项目文档沉淀'],
    compareWith: ['notion-ai', 'obsidian'],
  },

  {
    slug: 'meitu-ai', name: '美图秀秀AI', maker: '美图公司', logo: '📸',
    category: 'AI绘画', tagline: '国内最流行AI修图，一键美化人像图片',
    desc: '美图秀秀AI是国内用户基数最大的AI图像处理工具，集成AI抠图、AI修图、AI生图、AI换脸等功能，操作极其简单，无需任何设计基础，是普通用户快速美化图片的首选工具。',
    price: '免费', priceDetail: '基础功能免费，会员¥25/月解锁高级AI功能',
    pricePlans: [
      { name: '免费版', price: '¥0', period: '/月', features: ['基础AI美化', 'AI抠图', '基础滤镜', '每日免费次数'], highlight: true },
      { name: '会员', price: '¥25', period: '/月', features: ['无限AI功能', 'AI生图高清', 'AI换脸', '去水印'] },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 1, rating: 4.1, ratingCount: 3200,
    url: 'https://www.meitu.com',
    tags: ['AI修图', '国内', '免费', '人像', '图片处理'],
    features: ['AI一键美化', 'AI抠图', 'AI生图', 'AI换脸', '视频美颜', '证件照制作'],
    pros: ['操作极其简单无门槛', '国内直连免费使用', '用户基数大教程丰富', '移动端体验好'],
    cons: ['专业设计功能不足', 'AI生图质量弱于Midjourney', '高清输出需付费', '部分功能同质化'],
    bestFor: '普通用户、社交媒体内容创作者、电商商家',
    tutorials: [
      { title: '美图秀秀AI功能全攻略：AI抠图+生图+美化', url: 'https://search.bilibili.com/all?keyword=美图秀秀AI功能教程', platform: 'bilibili', duration: '8分钟', level: 'beginner' },
    ],
    useCases: ['人像照片美化', '证件照制作', '电商产品图处理', '社交媒体配图', 'AI艺术图生成'],
    compareWith: ['jimeng', 'canva', 'gaoding'],
  },

  {
    slug: 'tongyi-wanxiang', name: '通义万相', maker: '阿里巴巴', logo: '✨',
    category: 'AI绘画', tagline: '阿里出品AI绘画，中文提示词效果优秀',
    desc: '通义万相是阿里巴巴推出的AI图像生成工具，支持文生图、图生图、AI艺术创作等功能，中文提示词理解能力强，免费额度充足，国内直连无需翻墙，是即梦AI和文心一格的有力竞争者。',
    price: '免费', priceDetail: '注册即有免费积分，消耗完后按量付费',
    pricePlans: [
      { name: '免费版', price: '¥0', period: '注册赠送', features: ['免费积分', '文生图', '图生图', '多种风格'], highlight: true },
      { name: '按量付费', price: '¥0.04', period: '/张', features: ['高清1024px', '无水印', '商业授权'] },
    ],
    hasFree: true, hasApi: true, cnAccess: true, difficulty: 1, rating: 4.0, ratingCount: 760,
    url: 'https://tongyi.aliyun.com/wanxiang',
    tags: ['AI绘画', '国内', '阿里', '免费', '文生图'],
    features: ['文生图', '图生图', '风格迁移', '局部重绘', '中文提示词优化', '多分辨率支持'],
    pros: ['国内直连免费使用', '中文提示词理解好', '阿里云生态集成', '按量付费成本低'],
    cons: ['图像质量弱于Midjourney', '免费额度有限', '风格选项不如即梦丰富', '社区生态较弱'],
    bestFor: '国内中文用户、阿里云生态用户、AI绘画入门者',
    tutorials: [
      { title: '通义万相使用教程：阿里AI绘画免费体验', url: 'https://search.bilibili.com/all?keyword=通义万相使用教程', platform: 'bilibili', duration: '8分钟', level: 'beginner' },
    ],
    useCases: ['社交媒体配图', '商品展示图', '艺术创作', '封面设计', '中文场景图'],
    compareWith: ['jimeng', 'wenxin-yige', 'midjourney'],
  },

  {
    slug: 'markdown-nice', name: 'Markdown Nice', maker: '开源社区', logo: '✍️',
    category: '内容工具', tagline: 'Markdown转公众号格式，开发者写作首选',
    desc: 'Markdown Nice 是开源的Markdown转微信公众号排版工具，支持代码高亮、数学公式、多种主题，写完文章一键复制到公众号后台，格式完美保留。技术开发者写技术文章的首选排版工具。',
    price: '免费', priceDetail: '完全免费开源，无任何收费项目',
    pricePlans: [
      { name: '免费版', price: '¥0', period: '永久', features: ['Markdown实时预览', '20+排版主题', '代码语法高亮', '数学公式支持', '一键复制'], highlight: true },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 2, rating: 4.4, ratingCount: 890,
    url: 'https://mdnice.com',
    tags: ['Markdown', '公众号', '排版', '开源', '写作工具'],
    features: ['Markdown实时渲染', '微信公众号格式导出', '代码高亮', 'LaTeX数学公式', '20+主题模板', '图片上传'],
    pros: ['完全免费开源', '代码高亮效果极好', '数学公式完美渲染', '主题丰富一键切换'],
    cons: ['功能聚焦公众号场景', '对图文混排支持有限', '移动端体验较弱', '仅适合会写Markdown的用户'],
    bestFor: '技术开发者、写技术文章的公众号作者',
    tutorials: [
      { title: 'Markdown Nice教程：用Markdown写出漂亮的公众号', url: 'https://search.bilibili.com/all?keyword=Markdown+Nice教程', platform: 'bilibili', duration: '8分钟', level: 'beginner' },
    ],
    useCases: ['技术文章排版', '公众号内容发布', '代码教程写作', '数学公式文章', '开发日志分享'],
    compareWith: ['wps-ai'],
  },

  {
    slug: 'lseditor', name: '135编辑器', maker: '135编辑器', logo: '📝',
    category: '内容工具', tagline: '公众号排版神器，海量模板一键套用',
    desc: '135编辑器是国内最流行的微信公众号排版工具，提供数万款精美排版模板，支持AI写作辅助、一键美化、自定义样式，无需任何设计基础即可做出专业排版。是公众号运营者的日常必备工具。',
    price: '免费', priceDetail: '基础功能免费，会员¥99/年解锁全部模板',
    pricePlans: [
      { name: '免费版', price: '¥0', period: '/月', features: ['基础模板', 'AI写作（有限）', '基础排版功能', '复制到公众号'] },
      { name: '会员', price: '¥99', period: '/年', features: ['全部模板无限用', 'AI写作无限制', '自定义样式', '素材云存储'], highlight: true },
    ],
    hasFree: true, hasApi: false, cnAccess: true, difficulty: 1, rating: 4.3, ratingCount: 2100,
    url: 'https://www.135editor.com',
    tags: ['公众号', '排版', '国内', '模板', '微信'],
    features: ['数万款排版模板', 'AI写作辅助', '自定义颜色字体', '素材库', '一键复制到微信'],
    pros: ['模板数量多质量好', '操作极其简单', '国内直连无需翻墙', '免费版就能用'],
    cons: ['高级模板需付费', '自定义能力弱于代码排版', '广告较多', '页面加载有时稍慢'],
    bestFor: '公众号运营新手、企业新媒体编辑',
    tutorials: [
      { title: '135编辑器使用教程：公众号排版从入门到精通', url: 'https://search.bilibili.com/all?keyword=135编辑器使用教程', platform: 'bilibili', duration: '10分钟', level: 'beginner' },
    ],
    useCases: ['公众号图文排版', '企业新闻稿制作', '活动推文设计', '产品介绍文章', '节日营销内容'],
    compareWith: ['wps-ai'],
  },

  {
    slug: 'etsy', name: 'Etsy', maker: 'Etsy Inc.', logo: '🛒',
    category: '电商工具', tagline: '海外创意商品交易平台，AI绘画变现首选',
    desc: 'Etsy 是全球最大的手工艺品和创意商品交易市场，近年来成为AI绘画作品、数字产品变现的重要平台。卖家可以上架数字下载产品（如AI生成图、Prompt包、模板等），实现被动收入。',
    price: '按单收费', priceDetail: '上架费$0.20/件，成交后收取6.5%平台费',
    pricePlans: [
      { name: '卖家账号', price: '$0', period: '注册免费', features: ['免费开店', '数字产品销售', '全球买家触达', '数据统计'] },
      { name: '交易费用', price: '6.5%', period: '+$0.20/件', features: ['上架费$0.20', '交易佣金6.5%', 'Etsy广告可选', '支付处理费3%+$0.25'], highlight: true },
    ],
    hasFree: true, hasApi: false, cnAccess: false, difficulty: 2, rating: 4.0, ratingCount: 680,
    url: 'https://www.etsy.com',
    tags: ['电商', '数字产品', '创意市场', '被动收入', '海外变现'],
    features: ['数字下载产品销售', '全球2亿+买家', '搜索流量', 'Etsy广告系统', '评价体系', '数据分析'],
    pros: ['海外最大创意市场自带流量', '数字产品0库存成本', '被动收入一次制作永久销售', '支持PayPal收款'],
    cons: ['需要梯子和海外PayPal', '平台佣金累计较高', '竞争激烈同类商品多', '需要SEO优化才能获得流量'],
    bestFor: '想通过AI绘画和数字产品出海变现的创作者',
    tutorials: [
      { title: 'Etsy开店教程：AI绘画作品如何在海外变现', url: 'https://search.bilibili.com/all?keyword=Etsy开店教程+AI绘画', platform: 'bilibili', duration: '15分钟', level: 'beginner' },
      { title: 'Etsy SEO优化教程：让你的数字产品被更多人看到', url: 'https://www.youtube.com/results?search_query=etsy+seo+digital+products+tutorial+2025', platform: 'youtube', duration: '20分钟', level: 'advanced' },
    ],
    useCases: ['AI绘画作品销售', 'Prompt包销售', '设计模板出售', 'AI头像定制服务', '数字艺术变现'],
    compareWith: ['gaoding', 'canva'],
  },

  {
    slug: 'github', name: 'GitHub', maker: 'Microsoft', logo: '🐙',
    category: '开发工具', tagline: '全球最大代码托管平台，开发者必备',
    desc: 'GitHub 是全球最大的代码托管平台，基于Git版本控制，提供代码仓库、Issues、Pull Request、Actions CI/CD等功能。拥有1亿+开发者，是开源项目和协作开发的事实标准平台。',
    price: '免费起', priceDetail: '个人免费，Team $4/人/月，Enterprise $21/人/月',
    pricePlans: [
      { name: '免费版', price: '$0', period: '/月', features: ['无限公开仓库', '无限私有仓库', 'GitHub Actions 2000分钟/月', '社区支持'], highlight: true },
      { name: 'Team', price: '$4', period: '/人/月', features: ['所有免费功能', '无限Actions分钟', '代码审查', '高级安全功能'] },
    ],
    hasFree: true, hasApi: true, cnAccess: true, difficulty: 2, rating: 4.7, ratingCount: 3800,
    url: 'https://github.com',
    tags: ['代码托管', 'Git', '开源', 'CI/CD', '开发工具'],
    features: ['Git代码托管', 'GitHub Actions CI/CD', 'Pull Request代码审查', 'Issues项目管理', 'GitHub Pages', 'Copilot集成'],
    pros: ['开发者生态最完善', '免费功能非常全面', '与所有开发工具集成', '开源社区资源丰富'],
    cons: ['国内访问速度时有不稳定', '学习Git有一定曲线', '大文件存储限制', '企业私有化部署需付费'],
    bestFor: '所有软件开发者、开源项目维护者',
    tutorials: [
      { title: 'GitHub新手入门：从注册到提交第一行代码', url: 'https://search.bilibili.com/all?keyword=GitHub新手教程', platform: 'bilibili', duration: '20分钟', level: 'beginner' },
    ],
    useCases: ['代码版本管理', 'CI/CD自动化', '开源项目协作', '静态网站部署', '代码备份存储'],
    compareWith: ['cursor', 'codeium'],
  },
]

// 按分类分组
export function getToolsByCategory(): Record<string, Tool[]> {
  const result: Record<string, Tool[]> = {}
  ALL_TOOLS.forEach(tool => {
    if (!result[tool.category]) result[tool.category] = []
    result[tool.category].push(tool)
  })
  return result
}

// 获取所有分类
export function getAllCategories(): string[] {
  return [...new Set(ALL_TOOLS.map(t => t.category))]
}

// 按 slug 查找
export function getToolBySlug(slug: string): Tool | undefined {
  return ALL_TOOLS.find(t => t.slug === slug)
}

// 搜索工具
export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return ALL_TOOLS.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.tagline.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.toLowerCase().includes(q)) ||
    t.category.toLowerCase().includes(q)
  )
}
