import { NextRequest, NextResponse } from 'next/server'
const N='https://api.notion.com/v1', T=process.env.NOTION_API_KEY!, DB=process.env.NOTION_HOTKEYS_DB_ID!
const h = { Authorization:`Bearer ${T}`, 'Content-Type':'application/json', 'Notion-Version':'2022-06-28' }
const nR = (path: string, method='GET', body?: object) => fetch(`${N}${path}`, { method, headers:h, body:body?JSON.stringify(body):undefined }).then(r=>r.json())
const p2k = (p: any) => ({ id:p.id, label:p.properties?.label?.title?.[0]?.plain_text??'', query:p.properties?.query?.rich_text?.[0]?.plain_text??'', icon:p.properties?.icon?.rich_text?.[0]?.plain_text??'🔥', clickCount:p.properties?.clickCount?.number??0, searchCount:p.properties?.searchCount?.number??0, enabled:p.properties?.enabled?.checkbox??true, order:p.properties?.order?.number??99 })

export async function GET() { if(!DB) return NextResponse.json({keys:[]}); const d=await nR(`/databases/${DB}/query`,'POST',{page_size:50,sorts:[{property:'order',direction:'ascending'}]}); return NextResponse.json({keys:(d.results||[]).map(p2k)}) }
export async function POST(req: NextRequest) { if(!DB) return NextResponse.json({error:'DB未配置'},{status:500}); const b=await req.json(); await nR('/pages','POST',{parent:{database_id:DB},properties:{label:{title:[{text:{content:String(b.label||'')}}]},query:{rich_text:[{text:{content:String(b.query||'')}}]},icon:{rich_text:[{text:{content:String(b.icon||'🔥')}}]},enabled:{checkbox:b.enabled!==false},order:{number:Number(b.order)||99},clickCount:{number:0},searchCount:{number:0}}}); return NextResponse.json({created:true}) }
export async function PATCH(req: NextRequest) { const b=await req.json(); if(!b.id) return NextResponse.json({error:'缺少id'},{status:400}); const props:any={}; if(b.label!==undefined) props.label={title:[{text:{content:String(b.label)}}]}; if(b.query!==undefined) props.query={rich_text:[{text:{content:String(b.query)}}]}; if(b.icon!==undefined) props.icon={rich_text:[{text:{content:String(b.icon)}}]}; if(b.enabled!==undefined) props.enabled={checkbox:!!b.enabled}; if(b.order!==undefined) props.order={number:Number(b.order)}; await nR(`/pages/${b.id}`,'PATCH',{properties:props}); return NextResponse.json({updated:true}) }
export async function DELETE(req: NextRequest) { const id=new URL(req.url).searchParams.get('id'); if(!id) return NextResponse.json({error:'缺少id'},{status:400}); await nR(`/pages/${id}`,'PATCH',{archived:true}); return NextResponse.json({deleted:true}) }
